/**
 * Mule Intacct Cloud Connector
 *
 * (c) 2003-2012 MuleSoft, Inc. This software is protected under international
 * copyright law. All use of this software is subject to MuleSoft's Master
 * Subscription Agreement (or other Terms of Service) separately entered
 * into between you and MuleSoft. If such an agreement is not in
 * place, you may not use the software.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.20 at 12:04:27 PM ART 
//

package org.mule.module.intacct.schema.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"recordno", "vendorid", "vendorname", "paymenttype", "paymentdate",
    "receiptdate", "paymentamount", "documentnumber", "memo", "state", "status", "bankaccountid",
    "whenmodified", "termname", "cleared", "cleareddate", "systemgenerated", "vendordue", "currency",
    "paymenttrxamount"})
@XmlRootElement(name = "appaymentrequest")
public class Appaymentrequest
{

    protected String recordno;
    protected String vendorid;
    protected String vendorname;
    protected Paymenttype paymenttype;
    protected Paymentdate paymentdate;
    protected Receiptdate receiptdate;
    protected String paymentamount;
    protected String documentnumber;
    protected String memo;
    protected String state;
    protected String status;
    protected String bankaccountid;
    protected String whenmodified;
    protected String termname;
    protected Cleared cleared;
    protected Cleareddate cleareddate;
    protected Systemgenerated systemgenerated;
    protected Vendordue vendordue;
    protected String currency;
    protected String paymenttrxamount;

    /**
     * Gets the value of the recordno property.
     * 
     * @return possible object is {@link String }
     */
    public String getRecordno()
    {
        return recordno;
    }

    /**
     * Sets the value of the recordno property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setRecordno(String value)
    {
        this.recordno = value;
    }

    /**
     * Gets the value of the vendorid property.
     * 
     * @return possible object is {@link String }
     */
    public String getVendorid()
    {
        return vendorid;
    }

    /**
     * Sets the value of the vendorid property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setVendorid(String value)
    {
        this.vendorid = value;
    }

    /**
     * Gets the value of the vendorname property.
     * 
     * @return possible object is {@link String }
     */
    public String getVendorname()
    {
        return vendorname;
    }

    /**
     * Sets the value of the vendorname property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setVendorname(String value)
    {
        this.vendorname = value;
    }

    /**
     * Gets the value of the paymenttype property.
     * 
     * @return possible object is {@link Paymenttype }
     */
    public Paymenttype getPaymenttype()
    {
        return paymenttype;
    }

    /**
     * Sets the value of the paymenttype property.
     * 
     * @param value allowed object is {@link Paymenttype }
     */
    public void setPaymenttype(Paymenttype value)
    {
        this.paymenttype = value;
    }

    /**
     * Gets the value of the paymentdate property.
     * 
     * @return possible object is {@link Paymentdate }
     */
    public Paymentdate getPaymentdate()
    {
        return paymentdate;
    }

    /**
     * Sets the value of the paymentdate property.
     * 
     * @param value allowed object is {@link Paymentdate }
     */
    public void setPaymentdate(Paymentdate value)
    {
        this.paymentdate = value;
    }

    /**
     * Gets the value of the receiptdate property.
     * 
     * @return possible object is {@link Receiptdate }
     */
    public Receiptdate getReceiptdate()
    {
        return receiptdate;
    }

    /**
     * Sets the value of the receiptdate property.
     * 
     * @param value allowed object is {@link Receiptdate }
     */
    public void setReceiptdate(Receiptdate value)
    {
        this.receiptdate = value;
    }

    /**
     * Gets the value of the paymentamount property.
     * 
     * @return possible object is {@link String }
     */
    public String getPaymentamount()
    {
        return paymentamount;
    }

    /**
     * Sets the value of the paymentamount property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setPaymentamount(String value)
    {
        this.paymentamount = value;
    }

    /**
     * Gets the value of the documentnumber property.
     * 
     * @return possible object is {@link String }
     */
    public String getDocumentnumber()
    {
        return documentnumber;
    }

    /**
     * Sets the value of the documentnumber property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setDocumentnumber(String value)
    {
        this.documentnumber = value;
    }

    /**
     * Gets the value of the memo property.
     * 
     * @return possible object is {@link String }
     */
    public String getMemo()
    {
        return memo;
    }

    /**
     * Sets the value of the memo property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMemo(String value)
    {
        this.memo = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return possible object is {@link String }
     */
    public String getState()
    {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setState(String value)
    {
        this.state = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return possible object is {@link String }
     */
    public String getStatus()
    {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setStatus(String value)
    {
        this.status = value;
    }

    /**
     * Gets the value of the bankaccountid property.
     * 
     * @return possible object is {@link String }
     */
    public String getBankaccountid()
    {
        return bankaccountid;
    }

    /**
     * Sets the value of the bankaccountid property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setBankaccountid(String value)
    {
        this.bankaccountid = value;
    }

    /**
     * Gets the value of the whenmodified property.
     * 
     * @return possible object is {@link String }
     */
    public String getWhenmodified()
    {
        return whenmodified;
    }

    /**
     * Sets the value of the whenmodified property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setWhenmodified(String value)
    {
        this.whenmodified = value;
    }

    /**
     * Gets the value of the termname property.
     * 
     * @return possible object is {@link String }
     */
    public String getTermname()
    {
        return termname;
    }

    /**
     * Sets the value of the termname property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setTermname(String value)
    {
        this.termname = value;
    }

    /**
     * Gets the value of the cleared property.
     * 
     * @return possible object is {@link Cleared }
     */
    public Cleared getCleared()
    {
        return cleared;
    }

    /**
     * Sets the value of the cleared property.
     * 
     * @param value allowed object is {@link Cleared }
     */
    public void setCleared(Cleared value)
    {
        this.cleared = value;
    }

    /**
     * Gets the value of the cleareddate property.
     * 
     * @return possible object is {@link Cleareddate }
     */
    public Cleareddate getCleareddate()
    {
        return cleareddate;
    }

    /**
     * Sets the value of the cleareddate property.
     * 
     * @param value allowed object is {@link Cleareddate }
     */
    public void setCleareddate(Cleareddate value)
    {
        this.cleareddate = value;
    }

    /**
     * Gets the value of the systemgenerated property.
     * 
     * @return possible object is {@link Systemgenerated }
     */
    public Systemgenerated getSystemgenerated()
    {
        return systemgenerated;
    }

    /**
     * Sets the value of the systemgenerated property.
     * 
     * @param value allowed object is {@link Systemgenerated }
     */
    public void setSystemgenerated(Systemgenerated value)
    {
        this.systemgenerated = value;
    }

    /**
     * Gets the value of the vendordue property.
     * 
     * @return possible object is {@link Vendordue }
     */
    public Vendordue getVendordue()
    {
        return vendordue;
    }

    /**
     * Sets the value of the vendordue property.
     * 
     * @param value allowed object is {@link Vendordue }
     */
    public void setVendordue(Vendordue value)
    {
        this.vendordue = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return possible object is {@link String }
     */
    public String getCurrency()
    {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setCurrency(String value)
    {
        this.currency = value;
    }

    /**
     * Gets the value of the paymenttrxamount property.
     * 
     * @return possible object is {@link String }
     */
    public String getPaymenttrxamount()
    {
        return paymenttrxamount;
    }

    /**
     * Sets the value of the paymenttrxamount property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setPaymenttrxamount(String value)
    {
        this.paymenttrxamount = value;
    }

}
