/**
 * Mule Intacct Cloud Connector
 *
 * (c) 2003-2012 MuleSoft, Inc. This software is protected under international
 * copyright law. All use of this software is subject to MuleSoft's Master
 * Subscription Agreement (or other Terms of Service) separately entered
 * into between you and MuleSoft. If such an agreement is not in
 * place, you may not use the software.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.20 at 12:04:27 PM ART 
//

package org.mule.module.intacct.schema.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"record", "description", "chargecardid", "payee", "referenceno",
    "paymentdate", "ccpayitems"})
@XmlRootElement(name = "cctransaction")
public class Cctransaction
{

    protected Record record;
    protected String description;
    protected String chargecardid;
    protected String payee;
    protected String referenceno;
    protected Paymentdate paymentdate;
    @XmlElement(required = true)
    protected Ccpayitems ccpayitems;

    /**
     * Gets the value of the record property.
     * 
     * @return possible object is {@link Record }
     */
    public Record getRecord()
    {
        return record;
    }

    /**
     * Sets the value of the record property.
     * 
     * @param value allowed object is {@link Record }
     */
    public void setRecord(Record value)
    {
        this.record = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return possible object is {@link String }
     */
    public String getDescription()
    {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setDescription(String value)
    {
        this.description = value;
    }

    /**
     * Gets the value of the chargecardid property.
     * 
     * @return possible object is {@link String }
     */
    public String getChargecardid()
    {
        return chargecardid;
    }

    /**
     * Sets the value of the chargecardid property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setChargecardid(String value)
    {
        this.chargecardid = value;
    }

    /**
     * Gets the value of the payee property.
     * 
     * @return possible object is {@link String }
     */
    public String getPayee()
    {
        return payee;
    }

    /**
     * Sets the value of the payee property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setPayee(String value)
    {
        this.payee = value;
    }

    /**
     * Gets the value of the referenceno property.
     * 
     * @return possible object is {@link String }
     */
    public String getReferenceno()
    {
        return referenceno;
    }

    /**
     * Sets the value of the referenceno property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setReferenceno(String value)
    {
        this.referenceno = value;
    }

    /**
     * Gets the value of the paymentdate property.
     * 
     * @return possible object is {@link Paymentdate }
     */
    public Paymentdate getPaymentdate()
    {
        return paymentdate;
    }

    /**
     * Sets the value of the paymentdate property.
     * 
     * @param value allowed object is {@link Paymentdate }
     */
    public void setPaymentdate(Paymentdate value)
    {
        this.paymentdate = value;
    }

    /**
     * Gets the value of the ccpayitems property.
     * 
     * @return possible object is {@link Ccpayitems }
     */
    public Ccpayitems getCcpayitems()
    {
        return ccpayitems;
    }

    /**
     * Sets the value of the ccpayitems property.
     * 
     * @param value allowed object is {@link Ccpayitems }
     */
    public void setCcpayitems(Ccpayitems value)
    {
        this.ccpayitems = value;
    }

}
