//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.20 at 12:04:27 PM ART 
//

package org.mule.module.intacct.schema.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"reconmode", "apjournal", "arjournal"})
@XmlRootElement(name = "financialdata")
public class Financialdata
{

    @XmlElement(required = true)
    protected String reconmode;
    protected String apjournal;
    protected String arjournal;

    /**
     * Gets the value of the reconmode property.
     * 
     * @return possible object is {@link String }
     */
    public String getReconmode()
    {
        return reconmode;
    }

    /**
     * Sets the value of the reconmode property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setReconmode(String value)
    {
        this.reconmode = value;
    }

    /**
     * Gets the value of the apjournal property.
     * 
     * @return possible object is {@link String }
     */
    public String getApjournal()
    {
        return apjournal;
    }

    /**
     * Sets the value of the apjournal property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setApjournal(String value)
    {
        this.apjournal = value;
    }

    /**
     * Gets the value of the arjournal property.
     * 
     * @return possible object is {@link String }
     */
    public String getArjournal()
    {
        return arjournal;
    }

    /**
     * Sets the value of the arjournal property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setArjournal(String value)
    {
        this.arjournal = value;
    }

}
