//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.20 at 12:04:27 PM ART 
//

package org.mule.module.intacct.schema.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"budgetid", "description", "budgetdefault", "whencreated", "whenmodified",
    "userid", "status", "megadepartmentid", "megalocationid", "glbudgetitems"})
@XmlRootElement(name = "glbudget")
public class Glbudget
{

    @XmlElement(required = true)
    protected String budgetid;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String budgetdefault;
    protected Whencreated whencreated;
    protected String whenmodified;
    @XmlElement(required = true)
    protected String userid;
    protected String status;
    protected String megadepartmentid;
    protected String megalocationid;
    protected Glbudgetitems glbudgetitems;

    /**
     * Gets the value of the budgetid property.
     * 
     * @return possible object is {@link String }
     */
    public String getBudgetid()
    {
        return budgetid;
    }

    /**
     * Sets the value of the budgetid property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setBudgetid(String value)
    {
        this.budgetid = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return possible object is {@link String }
     */
    public String getDescription()
    {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setDescription(String value)
    {
        this.description = value;
    }

    /**
     * Gets the value of the budgetdefault property.
     * 
     * @return possible object is {@link String }
     */
    public String getBudgetdefault()
    {
        return budgetdefault;
    }

    /**
     * Sets the value of the budgetdefault property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setBudgetdefault(String value)
    {
        this.budgetdefault = value;
    }

    /**
     * Gets the value of the whencreated property.
     * 
     * @return possible object is {@link Whencreated }
     */
    public Whencreated getWhencreated()
    {
        return whencreated;
    }

    /**
     * Sets the value of the whencreated property.
     * 
     * @param value allowed object is {@link Whencreated }
     */
    public void setWhencreated(Whencreated value)
    {
        this.whencreated = value;
    }

    /**
     * Gets the value of the whenmodified property.
     * 
     * @return possible object is {@link String }
     */
    public String getWhenmodified()
    {
        return whenmodified;
    }

    /**
     * Sets the value of the whenmodified property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setWhenmodified(String value)
    {
        this.whenmodified = value;
    }

    /**
     * Gets the value of the userid property.
     * 
     * @return possible object is {@link String }
     */
    public String getUserid()
    {
        return userid;
    }

    /**
     * Sets the value of the userid property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setUserid(String value)
    {
        this.userid = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return possible object is {@link String }
     */
    public String getStatus()
    {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setStatus(String value)
    {
        this.status = value;
    }

    /**
     * Gets the value of the megadepartmentid property.
     * 
     * @return possible object is {@link String }
     */
    public String getMegadepartmentid()
    {
        return megadepartmentid;
    }

    /**
     * Sets the value of the megadepartmentid property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMegadepartmentid(String value)
    {
        this.megadepartmentid = value;
    }

    /**
     * Gets the value of the megalocationid property.
     * 
     * @return possible object is {@link String }
     */
    public String getMegalocationid()
    {
        return megalocationid;
    }

    /**
     * Sets the value of the megalocationid property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMegalocationid(String value)
    {
        this.megalocationid = value;
    }

    /**
     * Gets the value of the glbudgetitems property.
     * 
     * @return possible object is {@link Glbudgetitems }
     */
    public Glbudgetitems getGlbudgetitems()
    {
        return glbudgetitems;
    }

    /**
     * Sets the value of the glbudgetitems property.
     * 
     * @param value allowed object is {@link Glbudgetitems }
     */
    public void setGlbudgetitems(Glbudgetitems value)
    {
        this.glbudgetitems = value;
    }

}
