/**
 * Mule Intacct Cloud Connector
 *
 * (c) 2003-2012 MuleSoft, Inc. This software is protected under international
 * copyright law. All use of this software is subject to MuleSoft's Master
 * Subscription Agreement (or other Terms of Service) separately entered
 * into between you and MuleSoft. If such an agreement is not in
 * place, you may not use the software.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.20 at 12:04:27 PM ART 
//

package org.mule.module.intacct.schema.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"transdefid", "transclass"})
@XmlRootElement(name = "potransactiondef")
public class Potransactiondef
{

    protected String transdefid;
    protected String transclass;

    /**
     * Gets the value of the transdefid property.
     * 
     * @return possible object is {@link String }
     */
    public String getTransdefid()
    {
        return transdefid;
    }

    /**
     * Sets the value of the transdefid property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setTransdefid(String value)
    {
        this.transdefid = value;
    }

    /**
     * Gets the value of the transclass property.
     * 
     * @return possible object is {@link String }
     */
    public String getTransclass()
    {
        return transclass;
    }

    /**
     * Sets the value of the transclass property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setTransclass(String value)
    {
        this.transclass = value;
    }

}
