//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.20 at 12:04:27 PM ART 
//

package org.mule.module.intacct.schema.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"key", "projectid", "name", "taskno", "description", "ismilestone",
    "parenttaskname", "budgetqty", "estqty", "priority", "pbegindate", "penddate", "percentcomplete",
    "taskstatus", "utilized", "billable", "itemid", "taskresources"})
@XmlRootElement(name = "task")
public class Task
{

    protected Key key;
    protected String projectid;
    protected String name;
    protected String taskno;
    protected String description;
    protected String ismilestone;
    protected String parenttaskname;
    protected String budgetqty;
    protected String estqty;
    protected String priority;
    protected Pbegindate pbegindate;
    protected Penddate penddate;
    protected Percentcomplete percentcomplete;
    protected String taskstatus;
    protected String utilized;
    protected String billable;
    protected String itemid;
    protected Taskresources taskresources;

    /**
     * Gets the value of the key property.
     * 
     * @return possible object is {@link Key }
     */
    public Key getKey()
    {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value allowed object is {@link Key }
     */
    public void setKey(Key value)
    {
        this.key = value;
    }

    /**
     * Gets the value of the projectid property.
     * 
     * @return possible object is {@link String }
     */
    public String getProjectid()
    {
        return projectid;
    }

    /**
     * Sets the value of the projectid property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setProjectid(String value)
    {
        this.projectid = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     */
    public String getName()
    {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setName(String value)
    {
        this.name = value;
    }

    /**
     * Gets the value of the taskno property.
     * 
     * @return possible object is {@link String }
     */
    public String getTaskno()
    {
        return taskno;
    }

    /**
     * Sets the value of the taskno property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setTaskno(String value)
    {
        this.taskno = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return possible object is {@link String }
     */
    public String getDescription()
    {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setDescription(String value)
    {
        this.description = value;
    }

    /**
     * Gets the value of the ismilestone property.
     * 
     * @return possible object is {@link String }
     */
    public String getIsmilestone()
    {
        return ismilestone;
    }

    /**
     * Sets the value of the ismilestone property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setIsmilestone(String value)
    {
        this.ismilestone = value;
    }

    /**
     * Gets the value of the parenttaskname property.
     * 
     * @return possible object is {@link String }
     */
    public String getParenttaskname()
    {
        return parenttaskname;
    }

    /**
     * Sets the value of the parenttaskname property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setParenttaskname(String value)
    {
        this.parenttaskname = value;
    }

    /**
     * Gets the value of the budgetqty property.
     * 
     * @return possible object is {@link String }
     */
    public String getBudgetqty()
    {
        return budgetqty;
    }

    /**
     * Sets the value of the budgetqty property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setBudgetqty(String value)
    {
        this.budgetqty = value;
    }

    /**
     * Gets the value of the estqty property.
     * 
     * @return possible object is {@link String }
     */
    public String getEstqty()
    {
        return estqty;
    }

    /**
     * Sets the value of the estqty property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setEstqty(String value)
    {
        this.estqty = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return possible object is {@link String }
     */
    public String getPriority()
    {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setPriority(String value)
    {
        this.priority = value;
    }

    /**
     * Gets the value of the pbegindate property.
     * 
     * @return possible object is {@link Pbegindate }
     */
    public Pbegindate getPbegindate()
    {
        return pbegindate;
    }

    /**
     * Sets the value of the pbegindate property.
     * 
     * @param value allowed object is {@link Pbegindate }
     */
    public void setPbegindate(Pbegindate value)
    {
        this.pbegindate = value;
    }

    /**
     * Gets the value of the penddate property.
     * 
     * @return possible object is {@link Penddate }
     */
    public Penddate getPenddate()
    {
        return penddate;
    }

    /**
     * Sets the value of the penddate property.
     * 
     * @param value allowed object is {@link Penddate }
     */
    public void setPenddate(Penddate value)
    {
        this.penddate = value;
    }

    /**
     * Gets the value of the percentcomplete property.
     * 
     * @return possible object is {@link Percentcomplete }
     */
    public Percentcomplete getPercentcomplete()
    {
        return percentcomplete;
    }

    /**
     * Sets the value of the percentcomplete property.
     * 
     * @param value allowed object is {@link Percentcomplete }
     */
    public void setPercentcomplete(Percentcomplete value)
    {
        this.percentcomplete = value;
    }

    /**
     * Gets the value of the taskstatus property.
     * 
     * @return possible object is {@link String }
     */
    public String getTaskstatus()
    {
        return taskstatus;
    }

    /**
     * Sets the value of the taskstatus property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setTaskstatus(String value)
    {
        this.taskstatus = value;
    }

    /**
     * Gets the value of the utilized property.
     * 
     * @return possible object is {@link String }
     */
    public String getUtilized()
    {
        return utilized;
    }

    /**
     * Sets the value of the utilized property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setUtilized(String value)
    {
        this.utilized = value;
    }

    /**
     * Gets the value of the billable property.
     * 
     * @return possible object is {@link String }
     */
    public String getBillable()
    {
        return billable;
    }

    /**
     * Sets the value of the billable property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setBillable(String value)
    {
        this.billable = value;
    }

    /**
     * Gets the value of the itemid property.
     * 
     * @return possible object is {@link String }
     */
    public String getItemid()
    {
        return itemid;
    }

    /**
     * Sets the value of the itemid property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setItemid(String value)
    {
        this.itemid = value;
    }

    /**
     * Gets the value of the taskresources property.
     * 
     * @return possible object is {@link Taskresources }
     */
    public Taskresources getTaskresources()
    {
        return taskresources;
    }

    /**
     * Sets the value of the taskresources property.
     * 
     * @param value allowed object is {@link Taskresources }
     */
    public void setTaskresources(Taskresources value)
    {
        this.taskresources = value;
    }

}
