/*
 * Mule Intacct Cloud Connector
 *
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.20 at 12:04:27 PM ART 
//

package org.mule.module.intacct.schema.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"key", "title", "employeeid", "begindate", "enddate", "periodtype",
    "timesheetitems"})
@XmlRootElement(name = "timesheet")
public class Timesheet
{

    protected Key key;
    protected String title;
    protected Employeeid employeeid;
    protected Begindate begindate;
    protected Enddate enddate;
    protected Periodtype periodtype;
    protected Timesheetitems timesheetitems;

    /**
     * Gets the value of the key property.
     * 
     * @return possible object is {@link Key }
     */
    public Key getKey()
    {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value allowed object is {@link Key }
     */
    public void setKey(Key value)
    {
        this.key = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return possible object is {@link String }
     */
    public String getTitle()
    {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setTitle(String value)
    {
        this.title = value;
    }

    /**
     * Gets the value of the employeeid property.
     * 
     * @return possible object is {@link Employeeid }
     */
    public Employeeid getEmployeeid()
    {
        return employeeid;
    }

    /**
     * Sets the value of the employeeid property.
     * 
     * @param value allowed object is {@link Employeeid }
     */
    public void setEmployeeid(Employeeid value)
    {
        this.employeeid = value;
    }

    /**
     * Gets the value of the begindate property.
     * 
     * @return possible object is {@link Begindate }
     */
    public Begindate getBegindate()
    {
        return begindate;
    }

    /**
     * Sets the value of the begindate property.
     * 
     * @param value allowed object is {@link Begindate }
     */
    public void setBegindate(Begindate value)
    {
        this.begindate = value;
    }

    /**
     * Gets the value of the enddate property.
     * 
     * @return possible object is {@link Enddate }
     */
    public Enddate getEnddate()
    {
        return enddate;
    }

    /**
     * Sets the value of the enddate property.
     * 
     * @param value allowed object is {@link Enddate }
     */
    public void setEnddate(Enddate value)
    {
        this.enddate = value;
    }

    /**
     * Gets the value of the periodtype property.
     * 
     * @return possible object is {@link Periodtype }
     */
    public Periodtype getPeriodtype()
    {
        return periodtype;
    }

    /**
     * Sets the value of the periodtype property.
     * 
     * @param value allowed object is {@link Periodtype }
     */
    public void setPeriodtype(Periodtype value)
    {
        this.periodtype = value;
    }

    /**
     * Gets the value of the timesheetitems property.
     * 
     * @return possible object is {@link Timesheetitems }
     */
    public Timesheetitems getTimesheetitems()
    {
        return timesheetitems;
    }

    /**
     * Sets the value of the timesheetitems property.
     * 
     * @param value allowed object is {@link Timesheetitems }
     */
    public void setTimesheetitems(Timesheetitems value)
    {
        this.timesheetitems = value;
    }

}
