/*
 * Mule Intacct Cloud Connector
 *
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.20 at 12:04:27 PM ART 
//

package org.mule.module.intacct.schema.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"whsid", "cycle", "stdcost", "lastcost", "avgcost", "reordermethod",
    "economyorderqty", "reorder", "minorderqty", "maxorderqty", "minstock", "maxstock", "datelastsold",
    "datelastrecvd", "begbalqty", "begbalprice", "defaultsubsection"})
@XmlRootElement(name = "whslineitem")
public class Whslineitem
{

    @XmlElement(required = true)
    protected String whsid;
    protected String cycle;
    protected String stdcost;
    protected String lastcost;
    protected String avgcost;
    protected String reordermethod;
    protected String economyorderqty;
    protected String reorder;
    protected String minorderqty;
    protected String maxorderqty;
    protected String minstock;
    protected String maxstock;
    protected Datelastsold datelastsold;
    protected Datelastrecvd datelastrecvd;
    protected String begbalqty;
    protected String begbalprice;
    protected String defaultsubsection;

    /**
     * Gets the value of the whsid property.
     * 
     * @return possible object is {@link String }
     */
    public String getWhsid()
    {
        return whsid;
    }

    /**
     * Sets the value of the whsid property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setWhsid(String value)
    {
        this.whsid = value;
    }

    /**
     * Gets the value of the cycle property.
     * 
     * @return possible object is {@link String }
     */
    public String getCycle()
    {
        return cycle;
    }

    /**
     * Sets the value of the cycle property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setCycle(String value)
    {
        this.cycle = value;
    }

    /**
     * Gets the value of the stdcost property.
     * 
     * @return possible object is {@link String }
     */
    public String getStdcost()
    {
        return stdcost;
    }

    /**
     * Sets the value of the stdcost property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setStdcost(String value)
    {
        this.stdcost = value;
    }

    /**
     * Gets the value of the lastcost property.
     * 
     * @return possible object is {@link String }
     */
    public String getLastcost()
    {
        return lastcost;
    }

    /**
     * Sets the value of the lastcost property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setLastcost(String value)
    {
        this.lastcost = value;
    }

    /**
     * Gets the value of the avgcost property.
     * 
     * @return possible object is {@link String }
     */
    public String getAvgcost()
    {
        return avgcost;
    }

    /**
     * Sets the value of the avgcost property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setAvgcost(String value)
    {
        this.avgcost = value;
    }

    /**
     * Gets the value of the reordermethod property.
     * 
     * @return possible object is {@link String }
     */
    public String getReordermethod()
    {
        return reordermethod;
    }

    /**
     * Sets the value of the reordermethod property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setReordermethod(String value)
    {
        this.reordermethod = value;
    }

    /**
     * Gets the value of the economyorderqty property.
     * 
     * @return possible object is {@link String }
     */
    public String getEconomyorderqty()
    {
        return economyorderqty;
    }

    /**
     * Sets the value of the economyorderqty property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setEconomyorderqty(String value)
    {
        this.economyorderqty = value;
    }

    /**
     * Gets the value of the reorder property.
     * 
     * @return possible object is {@link String }
     */
    public String getReorder()
    {
        return reorder;
    }

    /**
     * Sets the value of the reorder property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setReorder(String value)
    {
        this.reorder = value;
    }

    /**
     * Gets the value of the minorderqty property.
     * 
     * @return possible object is {@link String }
     */
    public String getMinorderqty()
    {
        return minorderqty;
    }

    /**
     * Sets the value of the minorderqty property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMinorderqty(String value)
    {
        this.minorderqty = value;
    }

    /**
     * Gets the value of the maxorderqty property.
     * 
     * @return possible object is {@link String }
     */
    public String getMaxorderqty()
    {
        return maxorderqty;
    }

    /**
     * Sets the value of the maxorderqty property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMaxorderqty(String value)
    {
        this.maxorderqty = value;
    }

    /**
     * Gets the value of the minstock property.
     * 
     * @return possible object is {@link String }
     */
    public String getMinstock()
    {
        return minstock;
    }

    /**
     * Sets the value of the minstock property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMinstock(String value)
    {
        this.minstock = value;
    }

    /**
     * Gets the value of the maxstock property.
     * 
     * @return possible object is {@link String }
     */
    public String getMaxstock()
    {
        return maxstock;
    }

    /**
     * Sets the value of the maxstock property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMaxstock(String value)
    {
        this.maxstock = value;
    }

    /**
     * Gets the value of the datelastsold property.
     * 
     * @return possible object is {@link Datelastsold }
     */
    public Datelastsold getDatelastsold()
    {
        return datelastsold;
    }

    /**
     * Sets the value of the datelastsold property.
     * 
     * @param value allowed object is {@link Datelastsold }
     */
    public void setDatelastsold(Datelastsold value)
    {
        this.datelastsold = value;
    }

    /**
     * Gets the value of the datelastrecvd property.
     * 
     * @return possible object is {@link Datelastrecvd }
     */
    public Datelastrecvd getDatelastrecvd()
    {
        return datelastrecvd;
    }

    /**
     * Sets the value of the datelastrecvd property.
     * 
     * @param value allowed object is {@link Datelastrecvd }
     */
    public void setDatelastrecvd(Datelastrecvd value)
    {
        this.datelastrecvd = value;
    }

    /**
     * Gets the value of the begbalqty property.
     * 
     * @return possible object is {@link String }
     */
    public String getBegbalqty()
    {
        return begbalqty;
    }

    /**
     * Sets the value of the begbalqty property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setBegbalqty(String value)
    {
        this.begbalqty = value;
    }

    /**
     * Gets the value of the begbalprice property.
     * 
     * @return possible object is {@link String }
     */
    public String getBegbalprice()
    {
        return begbalprice;
    }

    /**
     * Sets the value of the begbalprice property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setBegbalprice(String value)
    {
        this.begbalprice = value;
    }

    /**
     * Gets the value of the defaultsubsection property.
     * 
     * @return possible object is {@link String }
     */
    public String getDefaultsubsection()
    {
        return defaultsubsection;
    }

    /**
     * Sets the value of the defaultsubsection property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setDefaultsubsection(String value)
    {
        this.defaultsubsection = value;
    }

}
