//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.20 at 12:04:16 PM ART 
//

package org.mule.module.intacct.schema.request;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"customerid", "paymentamount", "translatedamount",
    "batchkeyOrBankaccountidOrUndepfundsacct", "refid", "overpaylocid", "overpaydeptid", "datereceived",
    "paymentmethod", "basecurr", "currency", "exchratedateOrExchratetypeOrExchrate", "authcode",
    "arpaymentitem", "onlinecardpaymentOrOnlineachpayment"})
@XmlRootElement(name = "create_arpayment")
public class CreateArpayment
{

    @XmlElement(required = true)
    protected Customerid customerid;
    @XmlElement(required = true)
    protected Paymentamount paymentamount;
    protected String translatedamount;
    @XmlElements({@XmlElement(name = "batchkey", type = Batchkey.class),
        @XmlElement(name = "bankaccountid", type = Bankaccountid.class),
        @XmlElement(name = "undepfundsacct", type = Undepfundsacct.class)})
    protected List<Object> batchkeyOrBankaccountidOrUndepfundsacct;
    protected String refid;
    protected String overpaylocid;
    protected String overpaydeptid;
    protected Datereceived datereceived;
    protected String paymentmethod;
    protected String basecurr;
    protected String currency;
    @XmlElements({@XmlElement(name = "exchratedate", type = Exchratedate.class),
        @XmlElement(name = "exchratetype", type = Exchratetype.class),
        @XmlElement(name = "exchrate", type = Exchrate.class)})
    protected List<Object> exchratedateOrExchratetypeOrExchrate;
    protected String authcode;
    protected List<Arpaymentitem> arpaymentitem;
    @XmlElements({@XmlElement(name = "onlinecardpayment", type = Onlinecardpayment.class),
        @XmlElement(name = "onlineachpayment", type = Onlineachpayment.class)})
    protected List<Object> onlinecardpaymentOrOnlineachpayment;

    /**
     * Gets the value of the customerid property.
     * 
     * @return possible object is {@link Customerid }
     */
    public Customerid getCustomerid()
    {
        return customerid;
    }

    /**
     * Sets the value of the customerid property.
     * 
     * @param value allowed object is {@link Customerid }
     */
    public void setCustomerid(Customerid value)
    {
        this.customerid = value;
    }

    /**
     * Gets the value of the paymentamount property.
     * 
     * @return possible object is {@link Paymentamount }
     */
    public Paymentamount getPaymentamount()
    {
        return paymentamount;
    }

    /**
     * Sets the value of the paymentamount property.
     * 
     * @param value allowed object is {@link Paymentamount }
     */
    public void setPaymentamount(Paymentamount value)
    {
        this.paymentamount = value;
    }

    /**
     * Gets the value of the translatedamount property.
     * 
     * @return possible object is {@link String }
     */
    public String getTranslatedamount()
    {
        return translatedamount;
    }

    /**
     * Sets the value of the translatedamount property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setTranslatedamount(String value)
    {
        this.translatedamount = value;
    }

    /**
     * Gets the value of the batchkeyOrBankaccountidOrUndepfundsacct property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the batchkeyOrBankaccountidOrUndepfundsacct property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getBatchkeyOrBankaccountidOrUndepfundsacct().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Batchkey }
     * {@link Bankaccountid } {@link Undepfundsacct }
     */
    public List<Object> getBatchkeyOrBankaccountidOrUndepfundsacct()
    {
        if (batchkeyOrBankaccountidOrUndepfundsacct == null)
        {
            batchkeyOrBankaccountidOrUndepfundsacct = new ArrayList<Object>();
        }
        return this.batchkeyOrBankaccountidOrUndepfundsacct;
    }

    /**
     * Gets the value of the refid property.
     * 
     * @return possible object is {@link String }
     */
    public String getRefid()
    {
        return refid;
    }

    /**
     * Sets the value of the refid property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setRefid(String value)
    {
        this.refid = value;
    }

    /**
     * Gets the value of the overpaylocid property.
     * 
     * @return possible object is {@link String }
     */
    public String getOverpaylocid()
    {
        return overpaylocid;
    }

    /**
     * Sets the value of the overpaylocid property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setOverpaylocid(String value)
    {
        this.overpaylocid = value;
    }

    /**
     * Gets the value of the overpaydeptid property.
     * 
     * @return possible object is {@link String }
     */
    public String getOverpaydeptid()
    {
        return overpaydeptid;
    }

    /**
     * Sets the value of the overpaydeptid property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setOverpaydeptid(String value)
    {
        this.overpaydeptid = value;
    }

    /**
     * Gets the value of the datereceived property.
     * 
     * @return possible object is {@link Datereceived }
     */
    public Datereceived getDatereceived()
    {
        return datereceived;
    }

    /**
     * Sets the value of the datereceived property.
     * 
     * @param value allowed object is {@link Datereceived }
     */
    public void setDatereceived(Datereceived value)
    {
        this.datereceived = value;
    }

    /**
     * Gets the value of the paymentmethod property.
     * 
     * @return possible object is {@link String }
     */
    public String getPaymentmethod()
    {
        return paymentmethod;
    }

    /**
     * Sets the value of the paymentmethod property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setPaymentmethod(String value)
    {
        this.paymentmethod = value;
    }

    /**
     * Gets the value of the basecurr property.
     * 
     * @return possible object is {@link String }
     */
    public String getBasecurr()
    {
        return basecurr;
    }

    /**
     * Sets the value of the basecurr property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setBasecurr(String value)
    {
        this.basecurr = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return possible object is {@link String }
     */
    public String getCurrency()
    {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setCurrency(String value)
    {
        this.currency = value;
    }

    /**
     * Gets the value of the exchratedateOrExchratetypeOrExchrate property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the exchratedateOrExchratetypeOrExchrate property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getExchratedateOrExchratetypeOrExchrate().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Exchratedate }
     * {@link Exchratetype } {@link Exchrate }
     */
    public List<Object> getExchratedateOrExchratetypeOrExchrate()
    {
        if (exchratedateOrExchratetypeOrExchrate == null)
        {
            exchratedateOrExchratetypeOrExchrate = new ArrayList<Object>();
        }
        return this.exchratedateOrExchratetypeOrExchrate;
    }

    /**
     * Gets the value of the authcode property.
     * 
     * @return possible object is {@link String }
     */
    public String getAuthcode()
    {
        return authcode;
    }

    /**
     * Sets the value of the authcode property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setAuthcode(String value)
    {
        this.authcode = value;
    }

    /**
     * Gets the value of the arpaymentitem property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the arpaymentitem property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getArpaymentitem().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Arpaymentitem }
     */
    public List<Arpaymentitem> getArpaymentitem()
    {
        if (arpaymentitem == null)
        {
            arpaymentitem = new ArrayList<Arpaymentitem>();
        }
        return this.arpaymentitem;
    }

    /**
     * Gets the value of the onlinecardpaymentOrOnlineachpayment property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the onlinecardpaymentOrOnlineachpayment property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getOnlinecardpaymentOrOnlineachpayment().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Onlinecardpayment } {@link Onlineachpayment }
     */
    public List<Object> getOnlinecardpaymentOrOnlineachpayment()
    {
        if (onlinecardpaymentOrOnlineachpayment == null)
        {
            onlinecardpaymentOrOnlineachpayment = new ArrayList<Object>();
        }
        return this.onlinecardpaymentOrOnlineachpayment;
    }

}
