/*
 * Mule Intacct Cloud Connector
 *
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.20 at 12:04:16 PM ART 
//

package org.mule.module.intacct.schema.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "create_gltransactionType", propOrder = {"journalid", "datecreated", "description", "referenceno", "customfields",
    "gltransactionentries"})
@XmlRootElement(name = "create_gltransaction")
public class CreateGltransaction
{

    @XmlElement(required = true)
    protected String journalid;
    @XmlElement(required = true)
    protected Datecreated datecreated;
    @XmlElement(required = true)
    protected String description;
    protected String referenceno;
    protected Customfields customfields;
    @XmlElement(required = true)
    protected Gltransactionentries gltransactionentries;

    /**
     * Gets the value of the journalid property.
     * 
     * @return possible object is {@link String }
     */
    public String getJournalid()
    {
        return journalid;
    }

    /**
     * Sets the value of the journalid property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setJournalid(String value)
    {
        this.journalid = value;
    }

    /**
     * Gets the value of the datecreated property.
     * 
     * @return possible object is {@link Datecreated }
     */
    public Datecreated getDatecreated()
    {
        return datecreated;
    }

    /**
     * Sets the value of the datecreated property.
     * 
     * @param value allowed object is {@link Datecreated }
     */
    public void setDatecreated(Datecreated value)
    {
        this.datecreated = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return possible object is {@link String }
     */
    public String getDescription()
    {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setDescription(String value)
    {
        this.description = value;
    }

    /**
     * Gets the value of the referenceno property.
     * 
     * @return possible object is {@link String }
     */
    public String getReferenceno()
    {
        return referenceno;
    }

    /**
     * Sets the value of the referenceno property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setReferenceno(String value)
    {
        this.referenceno = value;
    }

    /**
     * Gets the value of the customfields property.
     * 
     * @return possible object is {@link Customfields }
     */
    public Customfields getCustomfields()
    {
        return customfields;
    }

    /**
     * Sets the value of the customfields property.
     * 
     * @param value allowed object is {@link Customfields }
     */
    public void setCustomfields(Customfields value)
    {
        this.customfields = value;
    }

    /**
     * Gets the value of the gltransactionentries property.
     * 
     * @return possible object is {@link Gltransactionentries }
     */
    public Gltransactionentries getGltransactionentries()
    {
        return gltransactionentries;
    }

    /**
     * Sets the value of the gltransactionentries property.
     * 
     * @param value allowed object is {@link Gltransactionentries }
     */
    public void setGltransactionentries(Gltransactionentries value)
    {
        this.gltransactionentries = value;
    }

}
