/**
 * Mule Intacct Cloud Connector
 *
 * (c) 2003-2012 MuleSoft, Inc. This software is protected under international
 * copyright law. All use of this software is subject to MuleSoft's Master
 * Subscription Agreement (or other Terms of Service) separately entered
 * into between you and MuleSoft. If such an agreement is not in
 * place, you may not use the software.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.20 at 12:04:16 PM ART 
//

package org.mule.module.intacct.schema.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "create_recurringstatgltransType", propOrder = {"journalid", "datecreated", "description", "referenceno", "startdate",
    "ending", "modenew", "interval", "eom", "errnotifyemailids", "revstartdate", "revending", "revmodenew",
    "revinterval", "reveom", "reverrnotifyemailids", "customfields", "statgltransactionentries"})
@XmlRootElement(name = "create_recurringstatgltrans")
public class CreateRecurringstatgltrans
{

    @XmlElement(required = true)
    protected String journalid;
    @XmlElement(required = true)
    protected Datecreated datecreated;
    @XmlElement(required = true)
    protected String description;
    protected String referenceno;
    @XmlElement(required = true)
    protected Startdate startdate;
    protected Ending ending;
    protected String modenew;
    protected String interval;
    protected String eom;
    protected String errnotifyemailids;
    protected Revstartdate revstartdate;
    protected Revending revending;
    protected String revmodenew;
    protected String revinterval;
    protected String reveom;
    protected String reverrnotifyemailids;
    protected Customfields customfields;
    @XmlElement(required = true)
    protected Statgltransactionentries statgltransactionentries;

    /**
     * Gets the value of the journalid property.
     * 
     * @return possible object is {@link String }
     */
    public String getJournalid()
    {
        return journalid;
    }

    /**
     * Sets the value of the journalid property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setJournalid(String value)
    {
        this.journalid = value;
    }

    /**
     * Gets the value of the datecreated property.
     * 
     * @return possible object is {@link Datecreated }
     */
    public Datecreated getDatecreated()
    {
        return datecreated;
    }

    /**
     * Sets the value of the datecreated property.
     * 
     * @param value allowed object is {@link Datecreated }
     */
    public void setDatecreated(Datecreated value)
    {
        this.datecreated = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return possible object is {@link String }
     */
    public String getDescription()
    {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setDescription(String value)
    {
        this.description = value;
    }

    /**
     * Gets the value of the referenceno property.
     * 
     * @return possible object is {@link String }
     */
    public String getReferenceno()
    {
        return referenceno;
    }

    /**
     * Sets the value of the referenceno property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setReferenceno(String value)
    {
        this.referenceno = value;
    }

    /**
     * Gets the value of the startdate property.
     * 
     * @return possible object is {@link Startdate }
     */
    public Startdate getStartdate()
    {
        return startdate;
    }

    /**
     * Sets the value of the startdate property.
     * 
     * @param value allowed object is {@link Startdate }
     */
    public void setStartdate(Startdate value)
    {
        this.startdate = value;
    }

    /**
     * Gets the value of the ending property.
     * 
     * @return possible object is {@link Ending }
     */
    public Ending getEnding()
    {
        return ending;
    }

    /**
     * Sets the value of the ending property.
     * 
     * @param value allowed object is {@link Ending }
     */
    public void setEnding(Ending value)
    {
        this.ending = value;
    }

    /**
     * Gets the value of the modenew property.
     * 
     * @return possible object is {@link String }
     */
    public String getModenew()
    {
        return modenew;
    }

    /**
     * Sets the value of the modenew property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setModenew(String value)
    {
        this.modenew = value;
    }

    /**
     * Gets the value of the interval property.
     * 
     * @return possible object is {@link String }
     */
    public String getInterval()
    {
        return interval;
    }

    /**
     * Sets the value of the interval property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setInterval(String value)
    {
        this.interval = value;
    }

    /**
     * Gets the value of the eom property.
     * 
     * @return possible object is {@link String }
     */
    public String getEom()
    {
        return eom;
    }

    /**
     * Sets the value of the eom property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setEom(String value)
    {
        this.eom = value;
    }

    /**
     * Gets the value of the errnotifyemailids property.
     * 
     * @return possible object is {@link String }
     */
    public String getErrnotifyemailids()
    {
        return errnotifyemailids;
    }

    /**
     * Sets the value of the errnotifyemailids property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setErrnotifyemailids(String value)
    {
        this.errnotifyemailids = value;
    }

    /**
     * Gets the value of the revstartdate property.
     * 
     * @return possible object is {@link Revstartdate }
     */
    public Revstartdate getRevstartdate()
    {
        return revstartdate;
    }

    /**
     * Sets the value of the revstartdate property.
     * 
     * @param value allowed object is {@link Revstartdate }
     */
    public void setRevstartdate(Revstartdate value)
    {
        this.revstartdate = value;
    }

    /**
     * Gets the value of the revending property.
     * 
     * @return possible object is {@link Revending }
     */
    public Revending getRevending()
    {
        return revending;
    }

    /**
     * Sets the value of the revending property.
     * 
     * @param value allowed object is {@link Revending }
     */
    public void setRevending(Revending value)
    {
        this.revending = value;
    }

    /**
     * Gets the value of the revmodenew property.
     * 
     * @return possible object is {@link String }
     */
    public String getRevmodenew()
    {
        return revmodenew;
    }

    /**
     * Sets the value of the revmodenew property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setRevmodenew(String value)
    {
        this.revmodenew = value;
    }

    /**
     * Gets the value of the revinterval property.
     * 
     * @return possible object is {@link String }
     */
    public String getRevinterval()
    {
        return revinterval;
    }

    /**
     * Sets the value of the revinterval property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setRevinterval(String value)
    {
        this.revinterval = value;
    }

    /**
     * Gets the value of the reveom property.
     * 
     * @return possible object is {@link String }
     */
    public String getReveom()
    {
        return reveom;
    }

    /**
     * Sets the value of the reveom property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setReveom(String value)
    {
        this.reveom = value;
    }

    /**
     * Gets the value of the reverrnotifyemailids property.
     * 
     * @return possible object is {@link String }
     */
    public String getReverrnotifyemailids()
    {
        return reverrnotifyemailids;
    }

    /**
     * Sets the value of the reverrnotifyemailids property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setReverrnotifyemailids(String value)
    {
        this.reverrnotifyemailids = value;
    }

    /**
     * Gets the value of the customfields property.
     * 
     * @return possible object is {@link Customfields }
     */
    public Customfields getCustomfields()
    {
        return customfields;
    }

    /**
     * Sets the value of the customfields property.
     * 
     * @param value allowed object is {@link Customfields }
     */
    public void setCustomfields(Customfields value)
    {
        this.customfields = value;
    }

    /**
     * Gets the value of the statgltransactionentries property.
     * 
     * @return possible object is {@link Statgltransactionentries }
     */
    public Statgltransactionentries getStatgltransactionentries()
    {
        return statgltransactionentries;
    }

    /**
     * Sets the value of the statgltransactionentries property.
     * 
     * @param value allowed object is {@link Statgltransactionentries }
     */
    public void setStatgltransactionentries(Statgltransactionentries value)
    {
        this.statgltransactionentries = value;
    }

}
