/*
 * Mule Intacct Cloud Connector
 *
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.20 at 12:04:16 PM ART 
//

package org.mule.module.intacct.schema.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "get_aragingType", propOrder = {"agingperiods", "customerid", "invoiceno", "locationid", "departmentid",
    "asofdate", "useduedate", "showdetails", "documenttype", "useglpostdate"})
@XmlRootElement(name = "get_araging")
public class GetAraging
{

    protected String agingperiods;
    protected Customerid customerid;
    protected String invoiceno;
    protected Locationid locationid;
    protected Departmentid departmentid;
    protected Asofdate asofdate;
    protected String useduedate;
    protected String showdetails;
    protected String documenttype;
    protected String useglpostdate;

    /**
     * Gets the value of the agingperiods property.
     * 
     * @return possible object is {@link String }
     */
    public String getAgingperiods()
    {
        return agingperiods;
    }

    /**
     * Sets the value of the agingperiods property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setAgingperiods(String value)
    {
        this.agingperiods = value;
    }

    /**
     * Gets the value of the customerid property.
     * 
     * @return possible object is {@link Customerid }
     */
    public Customerid getCustomerid()
    {
        return customerid;
    }

    /**
     * Sets the value of the customerid property.
     * 
     * @param value allowed object is {@link Customerid }
     */
    public void setCustomerid(Customerid value)
    {
        this.customerid = value;
    }

    /**
     * Gets the value of the invoiceno property.
     * 
     * @return possible object is {@link String }
     */
    public String getInvoiceno()
    {
        return invoiceno;
    }

    /**
     * Sets the value of the invoiceno property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setInvoiceno(String value)
    {
        this.invoiceno = value;
    }

    /**
     * Gets the value of the locationid property.
     * 
     * @return possible object is {@link Locationid }
     */
    public Locationid getLocationid()
    {
        return locationid;
    }

    /**
     * Sets the value of the locationid property.
     * 
     * @param value allowed object is {@link Locationid }
     */
    public void setLocationid(Locationid value)
    {
        this.locationid = value;
    }

    /**
     * Gets the value of the departmentid property.
     * 
     * @return possible object is {@link Departmentid }
     */
    public Departmentid getDepartmentid()
    {
        return departmentid;
    }

    /**
     * Sets the value of the departmentid property.
     * 
     * @param value allowed object is {@link Departmentid }
     */
    public void setDepartmentid(Departmentid value)
    {
        this.departmentid = value;
    }

    /**
     * Gets the value of the asofdate property.
     * 
     * @return possible object is {@link Asofdate }
     */
    public Asofdate getAsofdate()
    {
        return asofdate;
    }

    /**
     * Sets the value of the asofdate property.
     * 
     * @param value allowed object is {@link Asofdate }
     */
    public void setAsofdate(Asofdate value)
    {
        this.asofdate = value;
    }

    /**
     * Gets the value of the useduedate property.
     * 
     * @return possible object is {@link String }
     */
    public String getUseduedate()
    {
        return useduedate;
    }

    /**
     * Sets the value of the useduedate property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setUseduedate(String value)
    {
        this.useduedate = value;
    }

    /**
     * Gets the value of the showdetails property.
     * 
     * @return possible object is {@link String }
     */
    public String getShowdetails()
    {
        return showdetails;
    }

    /**
     * Sets the value of the showdetails property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setShowdetails(String value)
    {
        this.showdetails = value;
    }

    /**
     * Gets the value of the documenttype property.
     * 
     * @return possible object is {@link String }
     */
    public String getDocumenttype()
    {
        return documenttype;
    }

    /**
     * Sets the value of the documenttype property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setDocumenttype(String value)
    {
        this.documenttype = value;
    }

    /**
     * Gets the value of the useglpostdate property.
     * 
     * @return possible object is {@link String }
     */
    public String getUseglpostdate()
    {
        return useglpostdate;
    }

    /**
     * Sets the value of the useglpostdate property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setUseglpostdate(String value)
    {
        this.useglpostdate = value;
    }

}
