//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.20 at 12:04:16 PM ART 
//

package org.mule.module.intacct.schema.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "get_myclientsType", propOrder = {"companytype"})
@XmlRootElement(name = "get_myclients")
public class GetMyclients
{

    protected String companytype;

    /**
     * Gets the value of the companytype property.
     * 
     * @return possible object is {@link String }
     */
    public String getCompanytype()
    {
        return companytype;
    }

    /**
     * Sets the value of the companytype property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setCompanytype(String value)
    {
        this.companytype = value;
    }

}
