/**
 * Mule Intacct Cloud Connector
 *
 * (c) 2003-2012 MuleSoft, Inc. This software is protected under international
 * copyright law. All use of this software is subject to MuleSoft's Master
 * Subscription Agreement (or other Terms of Service) separately entered
 * into between you and MuleSoft. If such an agreement is not in
 * place, you may not use the software.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.20 at 12:04:16 PM ART 
//

package org.mule.module.intacct.schema.request;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "get_salestotalsType", propOrder = {"customerid", "reportingperiodnameOrStartdateOrEnddate"})
@XmlRootElement(name = "get_salestotals")
public class GetSalestotals
{

    protected Customerid customerid;
    @XmlElements({
        @XmlElement(name = "reportingperiodname", required = true, type = Reportingperiodname.class),
        @XmlElement(name = "startdate", required = true, type = Startdate.class),
        @XmlElement(name = "enddate", required = true, type = Enddate.class)})
    protected List<Object> reportingperiodnameOrStartdateOrEnddate;

    /**
     * Gets the value of the customerid property.
     * 
     * @return possible object is {@link Customerid }
     */
    public Customerid getCustomerid()
    {
        return customerid;
    }

    /**
     * Sets the value of the customerid property.
     * 
     * @param value allowed object is {@link Customerid }
     */
    public void setCustomerid(Customerid value)
    {
        this.customerid = value;
    }

    /**
     * Gets the value of the reportingperiodnameOrStartdateOrEnddate property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the reportingperiodnameOrStartdateOrEnddate property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getReportingperiodnameOrStartdateOrEnddate().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Reportingperiodname } {@link Startdate } {@link Enddate }
     */
    public List<Object> getReportingperiodnameOrStartdateOrEnddate()
    {
        if (reportingperiodnameOrStartdateOrEnddate == null)
        {
            reportingperiodnameOrStartdateOrEnddate = new ArrayList<Object>();
        }
        return this.reportingperiodnameOrStartdateOrEnddate;
    }

}
