/*
 * Mule Intacct Cloud Connector
 *
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.20 at 12:04:16 PM ART 
//

package org.mule.module.intacct.schema.request;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"accountlabelOrGlaccountno", "amount", "allocationid", "memo", "locationid",
    "departmentid", "item1099", "key", "totalpaid", "totaldue", "customfields", "revrectemplate",
    "defrevaccount", "revrecstartdate", "revrecenddate", "projectid", "customerid", "vendorid", "employeeid",
    "itemid", "classid", "billable"})
@XmlRootElement(name = "lineitem")
public class Lineitem
{

    @XmlElements({@XmlElement(name = "accountlabel", required = true, type = Accountlabel.class),
        @XmlElement(name = "glaccountno", required = true, type = Glaccountno.class)})
    protected List<Object> accountlabelOrGlaccountno;
    @XmlElement(required = true)
    protected String amount;
    protected String allocationid;
    protected String memo;
    protected Locationid locationid;
    protected Departmentid departmentid;
    protected String item1099;
    protected String key;
    protected String totalpaid;
    protected String totaldue;
    protected Customfields customfields;
    protected String revrectemplate;
    protected String defrevaccount;
    protected Revrecstartdate revrecstartdate;
    protected Revrecenddate revrecenddate;
    protected String projectid;
    protected Customerid customerid;
    protected Vendorid vendorid;
    protected Employeeid employeeid;
    protected Itemid itemid;
    protected String classid;
    protected String billable;

    /**
     * Gets the value of the accountlabelOrGlaccountno property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the accountlabelOrGlaccountno property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getAccountlabelOrGlaccountno().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Accountlabel }
     * {@link Glaccountno }
     */
    public List<Object> getAccountlabelOrGlaccountno()
    {
        if (accountlabelOrGlaccountno == null)
        {
            accountlabelOrGlaccountno = new ArrayList<Object>();
        }
        return this.accountlabelOrGlaccountno;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return possible object is {@link String }
     */
    public String getAmount()
    {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setAmount(String value)
    {
        this.amount = value;
    }

    /**
     * Gets the value of the allocationid property.
     * 
     * @return possible object is {@link String }
     */
    public String getAllocationid()
    {
        return allocationid;
    }

    /**
     * Sets the value of the allocationid property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setAllocationid(String value)
    {
        this.allocationid = value;
    }

    /**
     * Gets the value of the memo property.
     * 
     * @return possible object is {@link String }
     */
    public String getMemo()
    {
        return memo;
    }

    /**
     * Sets the value of the memo property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMemo(String value)
    {
        this.memo = value;
    }

    /**
     * Gets the value of the locationid property.
     * 
     * @return possible object is {@link Locationid }
     */
    public Locationid getLocationid()
    {
        return locationid;
    }

    /**
     * Sets the value of the locationid property.
     * 
     * @param value allowed object is {@link Locationid }
     */
    public void setLocationid(Locationid value)
    {
        this.locationid = value;
    }

    /**
     * Gets the value of the departmentid property.
     * 
     * @return possible object is {@link Departmentid }
     */
    public Departmentid getDepartmentid()
    {
        return departmentid;
    }

    /**
     * Sets the value of the departmentid property.
     * 
     * @param value allowed object is {@link Departmentid }
     */
    public void setDepartmentid(Departmentid value)
    {
        this.departmentid = value;
    }

    /**
     * Gets the value of the item1099 property.
     * 
     * @return possible object is {@link String }
     */
    public String getItem1099()
    {
        return item1099;
    }

    /**
     * Sets the value of the item1099 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setItem1099(String value)
    {
        this.item1099 = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return possible object is {@link String }
     */
    public String getKey()
    {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setKey(String value)
    {
        this.key = value;
    }

    /**
     * Gets the value of the totalpaid property.
     * 
     * @return possible object is {@link String }
     */
    public String getTotalpaid()
    {
        return totalpaid;
    }

    /**
     * Sets the value of the totalpaid property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setTotalpaid(String value)
    {
        this.totalpaid = value;
    }

    /**
     * Gets the value of the totaldue property.
     * 
     * @return possible object is {@link String }
     */
    public String getTotaldue()
    {
        return totaldue;
    }

    /**
     * Sets the value of the totaldue property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setTotaldue(String value)
    {
        this.totaldue = value;
    }

    /**
     * Gets the value of the customfields property.
     * 
     * @return possible object is {@link Customfields }
     */
    public Customfields getCustomfields()
    {
        return customfields;
    }

    /**
     * Sets the value of the customfields property.
     * 
     * @param value allowed object is {@link Customfields }
     */
    public void setCustomfields(Customfields value)
    {
        this.customfields = value;
    }

    /**
     * Gets the value of the revrectemplate property.
     * 
     * @return possible object is {@link String }
     */
    public String getRevrectemplate()
    {
        return revrectemplate;
    }

    /**
     * Sets the value of the revrectemplate property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setRevrectemplate(String value)
    {
        this.revrectemplate = value;
    }

    /**
     * Gets the value of the defrevaccount property.
     * 
     * @return possible object is {@link String }
     */
    public String getDefrevaccount()
    {
        return defrevaccount;
    }

    /**
     * Sets the value of the defrevaccount property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setDefrevaccount(String value)
    {
        this.defrevaccount = value;
    }

    /**
     * Gets the value of the revrecstartdate property.
     * 
     * @return possible object is {@link Revrecstartdate }
     */
    public Revrecstartdate getRevrecstartdate()
    {
        return revrecstartdate;
    }

    /**
     * Sets the value of the revrecstartdate property.
     * 
     * @param value allowed object is {@link Revrecstartdate }
     */
    public void setRevrecstartdate(Revrecstartdate value)
    {
        this.revrecstartdate = value;
    }

    /**
     * Gets the value of the revrecenddate property.
     * 
     * @return possible object is {@link Revrecenddate }
     */
    public Revrecenddate getRevrecenddate()
    {
        return revrecenddate;
    }

    /**
     * Sets the value of the revrecenddate property.
     * 
     * @param value allowed object is {@link Revrecenddate }
     */
    public void setRevrecenddate(Revrecenddate value)
    {
        this.revrecenddate = value;
    }

    /**
     * Gets the value of the projectid property.
     * 
     * @return possible object is {@link String }
     */
    public String getProjectid()
    {
        return projectid;
    }

    /**
     * Sets the value of the projectid property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setProjectid(String value)
    {
        this.projectid = value;
    }

    /**
     * Gets the value of the customerid property.
     * 
     * @return possible object is {@link Customerid }
     */
    public Customerid getCustomerid()
    {
        return customerid;
    }

    /**
     * Sets the value of the customerid property.
     * 
     * @param value allowed object is {@link Customerid }
     */
    public void setCustomerid(Customerid value)
    {
        this.customerid = value;
    }

    /**
     * Gets the value of the vendorid property.
     * 
     * @return possible object is {@link Vendorid }
     */
    public Vendorid getVendorid()
    {
        return vendorid;
    }

    /**
     * Sets the value of the vendorid property.
     * 
     * @param value allowed object is {@link Vendorid }
     */
    public void setVendorid(Vendorid value)
    {
        this.vendorid = value;
    }

    /**
     * Gets the value of the employeeid property.
     * 
     * @return possible object is {@link Employeeid }
     */
    public Employeeid getEmployeeid()
    {
        return employeeid;
    }

    /**
     * Sets the value of the employeeid property.
     * 
     * @param value allowed object is {@link Employeeid }
     */
    public void setEmployeeid(Employeeid value)
    {
        this.employeeid = value;
    }

    /**
     * Gets the value of the itemid property.
     * 
     * @return possible object is {@link Itemid }
     */
    public Itemid getItemid()
    {
        return itemid;
    }

    /**
     * Sets the value of the itemid property.
     * 
     * @param value allowed object is {@link Itemid }
     */
    public void setItemid(Itemid value)
    {
        this.itemid = value;
    }

    /**
     * Gets the value of the classid property.
     * 
     * @return possible object is {@link String }
     */
    public String getClassid()
    {
        return classid;
    }

    /**
     * Sets the value of the classid property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setClassid(String value)
    {
        this.classid = value;
    }

    /**
     * Gets the value of the billable property.
     * 
     * @return possible object is {@link String }
     */
    public String getBillable()
    {
        return billable;
    }

    /**
     * Sets the value of the billable property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setBillable(String value)
    {
        this.billable = value;
    }

}
