/**
 * Mule Intacct Cloud Connector
 *
 * (c) 2003-2012 MuleSoft, Inc. This software is protected under international
 * copyright law. All use of this software is subject to MuleSoft's Master
 * Subscription Agreement (or other Terms of Service) separately entered
 * into between you and MuleSoft. If such an agreement is not in
 * place, you may not use the software.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.20 at 12:04:16 PM ART 
//

package org.mule.module.intacct.schema.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"customerid", "itemid", "projectid", "taskname", "timetype", "locationid",
    "departmentid", "entrydate", "qty", "timesheetentrydescription", "notes", "vendorid", "classid",
    "customfields"})
@XmlRootElement(name = "timesheetitem")
public class Timesheetitem
{

    protected Customerid customerid;
    protected Itemid itemid;
    protected String projectid;
    protected String taskname;
    protected String timetype;
    protected Locationid locationid;
    protected Departmentid departmentid;
    @XmlElement(required = true)
    protected Entrydate entrydate;
    @XmlElement(required = true)
    protected String qty;
    protected String timesheetentrydescription;
    protected String notes;
    protected Vendorid vendorid;
    protected String classid;
    protected Customfields customfields;

    /**
     * Gets the value of the customerid property.
     * 
     * @return possible object is {@link Customerid }
     */
    public Customerid getCustomerid()
    {
        return customerid;
    }

    /**
     * Sets the value of the customerid property.
     * 
     * @param value allowed object is {@link Customerid }
     */
    public void setCustomerid(Customerid value)
    {
        this.customerid = value;
    }

    /**
     * Gets the value of the itemid property.
     * 
     * @return possible object is {@link Itemid }
     */
    public Itemid getItemid()
    {
        return itemid;
    }

    /**
     * Sets the value of the itemid property.
     * 
     * @param value allowed object is {@link Itemid }
     */
    public void setItemid(Itemid value)
    {
        this.itemid = value;
    }

    /**
     * Gets the value of the projectid property.
     * 
     * @return possible object is {@link String }
     */
    public String getProjectid()
    {
        return projectid;
    }

    /**
     * Sets the value of the projectid property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setProjectid(String value)
    {
        this.projectid = value;
    }

    /**
     * Gets the value of the taskname property.
     * 
     * @return possible object is {@link String }
     */
    public String getTaskname()
    {
        return taskname;
    }

    /**
     * Sets the value of the taskname property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setTaskname(String value)
    {
        this.taskname = value;
    }

    /**
     * Gets the value of the timetype property.
     * 
     * @return possible object is {@link String }
     */
    public String getTimetype()
    {
        return timetype;
    }

    /**
     * Sets the value of the timetype property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setTimetype(String value)
    {
        this.timetype = value;
    }

    /**
     * Gets the value of the locationid property.
     * 
     * @return possible object is {@link Locationid }
     */
    public Locationid getLocationid()
    {
        return locationid;
    }

    /**
     * Sets the value of the locationid property.
     * 
     * @param value allowed object is {@link Locationid }
     */
    public void setLocationid(Locationid value)
    {
        this.locationid = value;
    }

    /**
     * Gets the value of the departmentid property.
     * 
     * @return possible object is {@link Departmentid }
     */
    public Departmentid getDepartmentid()
    {
        return departmentid;
    }

    /**
     * Sets the value of the departmentid property.
     * 
     * @param value allowed object is {@link Departmentid }
     */
    public void setDepartmentid(Departmentid value)
    {
        this.departmentid = value;
    }

    /**
     * Gets the value of the entrydate property.
     * 
     * @return possible object is {@link Entrydate }
     */
    public Entrydate getEntrydate()
    {
        return entrydate;
    }

    /**
     * Sets the value of the entrydate property.
     * 
     * @param value allowed object is {@link Entrydate }
     */
    public void setEntrydate(Entrydate value)
    {
        this.entrydate = value;
    }

    /**
     * Gets the value of the qty property.
     * 
     * @return possible object is {@link String }
     */
    public String getQty()
    {
        return qty;
    }

    /**
     * Sets the value of the qty property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setQty(String value)
    {
        this.qty = value;
    }

    /**
     * Gets the value of the timesheetentrydescription property.
     * 
     * @return possible object is {@link String }
     */
    public String getTimesheetentrydescription()
    {
        return timesheetentrydescription;
    }

    /**
     * Sets the value of the timesheetentrydescription property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setTimesheetentrydescription(String value)
    {
        this.timesheetentrydescription = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return possible object is {@link String }
     */
    public String getNotes()
    {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setNotes(String value)
    {
        this.notes = value;
    }

    /**
     * Gets the value of the vendorid property.
     * 
     * @return possible object is {@link Vendorid }
     */
    public Vendorid getVendorid()
    {
        return vendorid;
    }

    /**
     * Sets the value of the vendorid property.
     * 
     * @param value allowed object is {@link Vendorid }
     */
    public void setVendorid(Vendorid value)
    {
        this.vendorid = value;
    }

    /**
     * Gets the value of the classid property.
     * 
     * @return possible object is {@link String }
     */
    public String getClassid()
    {
        return classid;
    }

    /**
     * Sets the value of the classid property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setClassid(String value)
    {
        this.classid = value;
    }

    /**
     * Gets the value of the customfields property.
     * 
     * @return possible object is {@link Customfields }
     */
    public Customfields getCustomfields()
    {
        return customfields;
    }

    /**
     * Sets the value of the customfields property.
     * 
     * @param value allowed object is {@link Customfields }
     */
    public void setCustomfields(Customfields value)
    {
        this.customfields = value;
    }

}
