/**
 * Mule Intacct Cloud Connector
 *
 * (c) 2003-2012 MuleSoft, Inc. This software is protected under international
 * copyright law. All use of this software is subject to MuleSoft's Master
 * Subscription Agreement (or other Terms of Service) separately entered
 * into between you and MuleSoft. If such an agreement is not in
 * place, you may not use the software.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.20 at 12:04:16 PM ART 
//

package org.mule.module.intacct.schema.request;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"glaccountnoOrAccountlabel", "description", "paymentamount", "departmentid",
    "locationid"})
@XmlRootElement(name = "updateccpayitem")
public class Updateccpayitem
{

    @XmlAttribute(name = "line_num", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lineNum;
    @XmlElements({@XmlElement(name = "glaccountno", type = Glaccountno.class),
        @XmlElement(name = "accountlabel", type = Accountlabel.class)})
    protected List<Object> glaccountnoOrAccountlabel;
    protected String description;
    protected Paymentamount paymentamount;
    protected Departmentid departmentid;
    protected Locationid locationid;

    /**
     * Gets the value of the lineNum property.
     * 
     * @return possible object is {@link String }
     */
    public String getLineNum()
    {
        return lineNum;
    }

    /**
     * Sets the value of the lineNum property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setLineNum(String value)
    {
        this.lineNum = value;
    }

    /**
     * Gets the value of the glaccountnoOrAccountlabel property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the glaccountnoOrAccountlabel property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getGlaccountnoOrAccountlabel().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Glaccountno }
     * {@link Accountlabel }
     */
    public List<Object> getGlaccountnoOrAccountlabel()
    {
        if (glaccountnoOrAccountlabel == null)
        {
            glaccountnoOrAccountlabel = new ArrayList<Object>();
        }
        return this.glaccountnoOrAccountlabel;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return possible object is {@link String }
     */
    public String getDescription()
    {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setDescription(String value)
    {
        this.description = value;
    }

    /**
     * Gets the value of the paymentamount property.
     * 
     * @return possible object is {@link Paymentamount }
     */
    public Paymentamount getPaymentamount()
    {
        return paymentamount;
    }

    /**
     * Sets the value of the paymentamount property.
     * 
     * @param value allowed object is {@link Paymentamount }
     */
    public void setPaymentamount(Paymentamount value)
    {
        this.paymentamount = value;
    }

    /**
     * Gets the value of the departmentid property.
     * 
     * @return possible object is {@link Departmentid }
     */
    public Departmentid getDepartmentid()
    {
        return departmentid;
    }

    /**
     * Sets the value of the departmentid property.
     * 
     * @param value allowed object is {@link Departmentid }
     */
    public void setDepartmentid(Departmentid value)
    {
        this.departmentid = value;
    }

    /**
     * Gets the value of the locationid property.
     * 
     * @return possible object is {@link Locationid }
     */
    public Locationid getLocationid()
    {
        return locationid;
    }

    /**
     * Sets the value of the locationid property.
     * 
     * @param value allowed object is {@link Locationid }
     */
    public void setLocationid(Locationid value)
    {
        this.locationid = value;
    }

}
