/*
 * $Id$
 * --------------------------------------------------------------------------------------
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */

package org.mule.module.intacct;

import org.mule.module.intacct.schema.request.*;

/**
 * {@link CommandType} : enumeration of commands that may be sent to intacct
 * 
 * @author flbulgarelli
 */
public enum CommandType implements EnumType
{
    CreateApaccountlabel(CreateApaccountlabel.class),
    CreateApadjustment(CreateApadjustment.class),
    CreateApadjustmentbatch(CreateApadjustmentbatch.class),
    CreateAraccountlabel(CreateAraccountlabel.class),
    CreateAradjustment(CreateAradjustment.class),
    CreateAradjustmentbatch(CreateAradjustmentbatch.class),
    CreateArpayment(CreateArpayment.class),
    CreateArpaymentbatch(CreateArpaymentbatch.class),
    CreateBill(CreateBill.class),
    CreateRecurringbill(CreateRecurringbill.class),
    CreateBillbatch(CreateBillbatch.class),
    CreateCheckingaccount(CreateCheckingaccount.class),
    CreateSavingsaccount(CreateSavingsaccount.class),
    UpdateCheckingaccount(UpdateCheckingaccount.class),
    UpdateSavingsaccount(UpdateSavingsaccount.class),
    DeleteCheckingaccount(DeleteCheckingaccount.class),
    DeleteSavingsaccount(DeleteSavingsaccount.class),
    CreateContact(CreateContact.class),
    CreateCustomer(CreateCustomer.class),
    CreateDepartment(CreateDepartment.class),
    CreateEmployee(CreateEmployee.class),
    CreateExpensereport(CreateExpensereport.class),
    CreateExpensereportbatch(CreateExpensereportbatch.class),
    CreateExpensetype(CreateExpensetype.class),
    CreateGlaccount(CreateGlaccount.class),
    CreateStatglaccount(CreateStatglaccount.class),
    CreateGltransaction(CreateGltransaction.class),
    DeleteGltransaction(DeleteGltransaction.class),
    CreateRecurringgltransaction(CreateRecurringgltransaction.class),
    DeleteRecurringgltransaction(DeleteRecurringgltransaction.class),
    CreateStatgltransaction(CreateStatgltransaction.class),
    CreateRecurringstatgltrans(CreateRecurringstatgltrans.class),
    DeleteRecurringstatgltrans(DeleteRecurringstatgltrans.class),
    CreateInvoice(CreateInvoice.class),
    CreateRecurringinvoice(CreateRecurringinvoice.class),
    CreateInvoicebatch(CreateInvoicebatch.class),
    CreateJournal(CreateJournal.class),
    CreateLocation(CreateLocation.class),
    CreateStatjournal(CreateStatjournal.class),
    CreateProject(CreateProject.class),
    UpdateProject(UpdateProject.class),
    DeleteProject(DeleteProject.class),
    CreateClass(CreateClass.class),
    DeleteClass(DeleteClass.class),
    CreateVendor(CreateVendor.class),
    DeleteApaccountlabel(DeleteApaccountlabel.class),
    DeleteApadjustment(DeleteApadjustment.class),
    CreateLocationgroup(CreateLocationgroup.class),
    DeleteAraccountlabel(DeleteAraccountlabel.class),
    DeleteAradjustment(DeleteAradjustment.class),
    DeleteBill(DeleteBill.class),
    DeleteRecurringbill(DeleteRecurringbill.class),
    DeleteContact(DeleteContact.class),
    DeleteCustomer(DeleteCustomer.class),
    DeleteDepartment(DeleteDepartment.class),
    DeleteEmployee(DeleteEmployee.class),
    DeleteExpensereport(DeleteExpensereport.class),
    DeleteExpensetype(DeleteExpensetype.class),
    DeleteGlaccount(DeleteGlaccount.class),
    DeleteStatglaccount(DeleteStatglaccount.class),
    DeleteInvoice(DeleteInvoice.class),
    DeleteRecurringinvoice(DeleteRecurringinvoice.class),
    DeleteJournal(DeleteJournal.class),
    DeleteStatjournal(DeleteStatjournal.class),
    DeleteLocation(DeleteLocation.class),
    DeleteVendor(DeleteVendor.class),
    Get(Get.class),
    GetAccountbalances(GetAccountbalances.class),
    GetAccountgroupdetails(GetAccountgroupdetails.class),
    GetApadjustment(GetApadjustment.class),
    GetAradjustment(GetAradjustment.class),
    GetBill(GetBill.class),
    GetExpensereport(GetExpensereport.class),
    GetInvoice(GetInvoice.class),
    GetList(GetList.class),
    GetTrialbalance(GetTrialbalance.class),
    GetMyclients(GetMyclients.class),
    InitSession(InitSession.class),
    UpdateApaccountlabel(UpdateApaccountlabel.class),
    UpdateAraccountlabel(UpdateAraccountlabel.class),
    UpdateContact(UpdateContact.class),
    UpdateCustomer(UpdateCustomer.class),
    UpdateDepartment(UpdateDepartment.class),
    UpdateInvoice(UpdateInvoice.class),
    UpdateBill(UpdateBill.class),
    UpdateApadjustment(UpdateApadjustment.class),
    UpdateAradjustment(UpdateAradjustment.class),
    UpdateEmployee(UpdateEmployee.class),
    UpdateExpensereport(UpdateExpensereport.class),
    UpdateExpensetype(UpdateExpensetype.class),
    UpdateGlaccount(UpdateGlaccount.class),
    UpdateStatglaccount(UpdateStatglaccount.class),
    UpdateJournal(UpdateJournal.class),
    UpdateLocation(UpdateLocation.class),
    UpdateVendor(UpdateVendor.class),
    CreatePaymentrequest(CreatePaymentrequest.class),
    ReclassifyBill(ReclassifyBill.class),
    ReclassifyInvoice(ReclassifyInvoice.class),
    DeletePaymentrequest(DeletePaymentrequest.class),
    CreateAppayment(CreateAppayment.class),
    CreateStkittransaction(CreateStkittransaction.class),
    CreateIctransaction(CreateIctransaction.class),
    UpdateIctransaction(UpdateIctransaction.class),
    CreateSotransaction(CreateSotransaction.class),
    UpdateSotransaction(UpdateSotransaction.class),
    CreateRecursotransaction(CreateRecursotransaction.class),
    DeleteRecursotransaction(DeleteRecursotransaction.class),
    CreatePotransaction(CreatePotransaction.class),
    UpdatePotransaction(UpdatePotransaction.class),
    GetSalestotals(GetSalestotals.class),
    GetIcitemtotals(GetIcitemtotals.class),
    RecordCctransaction(RecordCctransaction.class),
    RecordWucctransactions(RecordWucctransactions.class),
    RecordWureceipts(RecordWureceipts.class),
    RecordWudisbursements(RecordWudisbursements.class),
    RecordWuadjjournalentries(RecordWuadjjournalentries.class),
    RecordWujournalentries(RecordWujournalentries.class),
    GetCompanyprefs(GetCompanyprefs.class),
    SetCompanyprefs(SetCompanyprefs.class),
    GetApplications(GetApplications.class),
    RecordOtherreceipt(RecordOtherreceipt.class),
    RecordDeposit(RecordDeposit.class),
    CreateTerritory(CreateTerritory.class),
    DeleteTerritory(DeleteTerritory.class),
    UpdateTerritory(UpdateTerritory.class),
    ApplyArpayment(ApplyArpayment.class),
    DeleteSotransaction(DeleteSotransaction.class),
    DeletePotransaction(DeletePotransaction.class),
    DeleteIctransaction(DeleteIctransaction.class),
    CreateItem(CreateItem.class),
    UpdateItem(UpdateItem.class),
    DeleteItem(DeleteItem.class),
    CreateSopricelist(CreateSopricelist.class),
    DeleteSopricelist(DeleteSopricelist.class),
    UpdateSopricelist(UpdateSopricelist.class),
    CreatePopricelist(CreatePopricelist.class),
    DeletePopricelist(DeletePopricelist.class),
    UpdatePopricelist(UpdatePopricelist.class),
    CreateVsoepricelist(CreateVsoepricelist.class),
    UpdateVsoepricelist(UpdateVsoepricelist.class),
    DeleteVsoepricelist(DeleteVsoepricelist.class),
    CreateVsoeitempricelist(CreateVsoeitempricelist.class),
    UpdateVsoeitempricelist(UpdateVsoeitempricelist.class),
    DeleteVsoeitempricelist(DeleteVsoeitempricelist.class),
    CreateInvpricelistentry(CreateInvpricelistentry.class),
    DeleteInvpricelistentry(DeleteInvpricelistentry.class),
    UpdateInvpricelistentry(UpdateInvpricelistentry.class),
    GetClosedbooksdate(GetClosedbooksdate.class),
    GetAraging(GetAraging.class),
    DeleteArpayment(DeleteArpayment.class),
    CreateCustomerachinfo(CreateCustomerachinfo.class),
    UpdateCustomerachinfo(UpdateCustomerachinfo.class),
    DeleteCustomerachinfo(DeleteCustomerachinfo.class),
    CreateCustomerchargecard(CreateCustomerchargecard.class),
    UpdateCustomerchargecard(UpdateCustomerchargecard.class),
    DeleteCustomerchargecard(DeleteCustomerchargecard.class),
    CreateCustomerbankaccount(CreateCustomerbankaccount.class),
    UpdateCustomerbankaccount(UpdateCustomerbankaccount.class),
    DeleteCustomerbankaccount(DeleteCustomerbankaccount.class),
    CreateTaxdetail(CreateTaxdetail.class),
    UpdateTaxdetail(UpdateTaxdetail.class),
    DeleteTaxdetail(DeleteTaxdetail.class),
    CreateTaxschedule(CreateTaxschedule.class),
    UpdateTaxschedule(UpdateTaxschedule.class),
    DeleteTaxschedule(DeleteTaxschedule.class),
    CreateTaxscheduledetail(CreateTaxscheduledetail.class),
    DeleteTaxscheduledetail(DeleteTaxscheduledetail.class),
    CreateContacttaxgroup(CreateContacttaxgroup.class),
    DeleteContacttaxgroup(DeleteContacttaxgroup.class),
    CreateItemtaxgroup(CreateItemtaxgroup.class),
    DeleteItemtaxgroup(DeleteItemtaxgroup.class),
    CreateTaxschedulemap(CreateTaxschedulemap.class),
    DeleteTaxschedulemap(DeleteTaxschedulemap.class),
    Describe(Describe.class),
    ReconcileBank(ReconcileBank.class),
    ReverseBill(ReverseBill.class),
    ReverseAppayment(ReverseAppayment.class),
    CreateApterm(CreateApterm.class),
    UpdateApterm(UpdateApterm.class),
    DeleteApterm(DeleteApterm.class),
    CreateArterm(CreateArterm.class),
    UpdateArterm(UpdateArterm.class),
    DeleteArterm(DeleteArterm.class),
    CreateTimesheet(CreateTimesheet.class),
    UpdateTimesheet(UpdateTimesheet.class),
    DeleteTimesheet(DeleteTimesheet.class),
    CreateTask(CreateTask.class),
    UpdateTask(UpdateTask.class),
    DeleteTask(DeleteTask.class),
    CreateAllocation(CreateAllocation.class),
    UpdateAllocation(UpdateAllocation.class),
    DeleteAllocation(DeleteAllocation.class),
    UpdateCctransaction(UpdateCctransaction.class),
    ReverseCctransaction(ReverseCctransaction.class);
    
    private Class<?> requestType;

    private CommandType(Class<?> requestType){
        this.requestType = requestType;
    }
    
    @Override
    public Class<?> getRequestType()
    {
        return requestType;
    }

}


