/**
 * Mule Development Kit
 * Copyright 2010-2011 (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.module.intacct;

import org.mule.api.annotations.Configurable;
import org.mule.api.annotations.Module;
import org.mule.api.annotations.Processor;
import org.mule.api.annotations.param.Optional;
import org.mule.module.intacct.exception.IntacctException;
import org.mule.module.intacct.impl.JerseySslIntacctFacade;
import org.mule.module.intacct.schema.request.Arpaymentitem;
import org.mule.module.intacct.schema.request.Arpaymentitems;
import org.mule.module.intacct.schema.request.Authentication;
import org.mule.module.intacct.schema.request.Content;
import org.mule.module.intacct.schema.request.Control;
import org.mule.module.intacct.schema.request.CreateAradjustment;
import org.mule.module.intacct.schema.request.CreateInvoice;
import org.mule.module.intacct.schema.request.CreateInvoicebatch;
import org.mule.module.intacct.schema.request.CreateSotransaction;
import org.mule.module.intacct.schema.request.Customfield;
import org.mule.module.intacct.schema.request.Function;
import org.mule.module.intacct.schema.request.Get;
import org.mule.module.intacct.schema.request.GetList;
import org.mule.module.intacct.schema.request.Invoiceitems;
import org.mule.module.intacct.schema.request.Lineitem;
import org.mule.module.intacct.schema.request.Login;
import org.mule.module.intacct.schema.request.Operation;
import org.mule.module.intacct.schema.request.Request;
import org.mule.module.intacct.schema.response.Response;
import org.mule.module.intacct.utils.MapBuilder;

import ar.com.zauber.commons.mom.CXFStyle;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.xml.bind.JAXBException;

@SuppressWarnings("serial")
@Module(name="intacct",
        namespace="http://repository.mulesoft.org/releases/org/mule/modules/mule-module-intacct",
        schemaLocation="http://repository.mulesoft.org/releases/org/mule/modules/mule-module-intacct/1.0-SNAPSHOT/mule-intacct.xsd")
public class IntacctCloudConnector
{
    @Configurable
    private String senderId;
    
    @Configurable
    private String controlPassword;
    
    @Configurable
    private String controlid;
    
    @Configurable
    private String uniqueid;
    
    @Configurable
    private String userid;
    
    @Configurable
    private String userPassword;
    
    @Configurable
    private String companyid;
    
    @Configurable
    @Optional
    private IntacctFacade intacctImplementation;
    
    private MapObjectMapper mom =  new MapObjectMapper("org.mule.module.intacct.schema");
    

    private static final String URL = "https://www.intacct.com/ia/xml/xmlgw.phtml";

    /** 
     * Given the function we create the request with the parameters for default given in the config 
     * @deprecated use {@link #execute(CommandType, List)} instead
     * */
    @Deprecated
    @Processor
    public Response operation(final Map<String, Object> function) throws JAXBException
    {
        Function realFunction = mom.toObject(Function.class, function);

        return operationWithRequest(inicializeRequest(realFunction));
    }
    
    
    /**
     * Batch executes a list of commands of the given CommandType.
     * 
     * Example 1:
     * 
     * {@code <intacct:execute type="CreateBill">
     *          <intacct:commands>
     *              <intacct:command>
     *                  <externalid>#[variable:aString]</externalid>
     *                  <description>#[variable:anotherString]</description>
     *                  <batchkey>#[variable:aBatchkeyOrStringObjectMap]</batchkey>
     *                  <!-- ...etc... -->
     *              <intacct:command>
     *          </intacct:commands>
     *        </intacct:execute> }
     *        
     * Example 2:
     * 
     * {@code <intacct:execute type="CreateBill">
     *          <intacct:commands ref="#[variable:aListOfStringObjectMaps]"/>
     *        </intacct:execute>}
     * 
     * 
     * Example 3:
     * 
     * {@code <intacct:execute type="CreateBill">
     *          <intacct:commands ref="#[groovy:[
     *              [ 'externalId' : 'anId',
     *                'description' : 'aDescription',
     *                'batchkey' : [ 'value' : 'aBatchkeyValue' ],
     *                 // ... etc ...
     *              ]
     *          ]]"/>
     *        </intacct:execute>}
     * 
     *  
     * @param type the type of commands to execute
     * @param commands the commands list
     * @return the response
     */
    @Processor
    public Response execute(final CommandType type, final List<Map<String, Object>> commands) throws JAXBException
    {
        return operation(mom.wrapList("cmd", commands, type.getRequestType()));
    }
    

    /**
     * Creates an {@link org.mule.module.intacct.schema.response.Invoice}
     */
    @Processor
    public Response createInvoice(String functionControlId,
                                  String customerId,
                                  Map<String, Object> dateCreated,
                                  @Optional Map<String, Object> datePosted,
                                  @Optional Map<String, Object> dateDue,
                                  @Optional String termName,
                                  @Optional String batchKey,
                                  @Optional String invoiceNo,
                                  @Optional String poNumber,
                                  @Optional String description,
                                  @Optional String externalId,
                                  @Optional ContactType billToContactType,
                                  @Optional List<Map<String, Object>> billTo,
                                  @Optional ContactType shipToContactType,
                                  @Optional List<Map<String, Object>> shipTo,
                                  @Optional String baseCurr,
                                  @Optional String currency,
                                  @Optional ExchType exchType,
                                  @Optional List<Map<String, Object>> exchRateDateOrExchRateTypeOrExchRate,
                                  @Optional String nogl,
                                  @Optional List<Map<String, Object>> customFields,
                                  Invoiceitems invoiceitems) throws JAXBException
    {      
    	List<Object> exchRateDateOrExchRateTypeOrExchRateAux = new ArrayList<Object>();
    	if(exchRateDateOrExchRateTypeOrExchRate != null){
        	for(Map<String, Object> exch : exchRateDateOrExchRateTypeOrExchRate)
        	{
        		exchRateDateOrExchRateTypeOrExchRateAux.add(mom.toObject(exchType.getRequestType(), exch));
        	}
        }
        
        CreateInvoice createInvoice = mom.toObject(CreateInvoice.class, 
            new MapBuilder().with("customerid", fromSingleValue(customerId))
                            .with("datecreated", dateCreated)
                            .with("dateposted", datePosted)
                            .with("datedue", dateDue)
                            .with("termname", fromSingleValue(termName))
                            .with("batchkey", fromSingleValue(batchKey))
                            .with("invoiceno", invoiceNo)
                            .with("ponumber", poNumber)
                            .with("description", description)
                            .with("externalId", externalId)
                            .with("shipto", nullifyEmptyListWrapper("contactOrContactname", shipTo, shipToContactType.getRequestType()))
                            .with("billto", nullifyEmptyListWrapper("contactOrContactname", billTo, billToContactType.getRequestType()))
                            .with("basecurr", baseCurr)
                            .with("currency", currency)
                            .with("exchratedateOrExchratetypeOrExchrate", coalesceList(exchRateDateOrExchRateTypeOrExchRateAux))
                            .with("nogl", nogl)
                            .with("customfields", nullifyEmptyListWrapper("customfield", customFields, Customfield.class))
                            .build());

        Function function = new Function();
        function.getCmd().add(createInvoice);
        function.setControlid(functionControlId);
        
        return operationWithRequest(inicializeRequest(function));
    }
    
    /**
     * Creates an {@link org.mule.module.intacct.schema.response.Invoicebatch}
     */
    @Processor
    public Response createInvoicebatch(String functionControlId,
                                       String batchTitle,
                                       @Optional Map<String, Object> dateCreated,
                                       @Optional List<Map<String, Object>> createInvoiceList
                                       ) throws JAXBException
    {
        List<CreateInvoice> createInvoiceListAux = new ArrayList<CreateInvoice>();
        if(createInvoiceList != null){
        	for(Map<String, Object> invoice : createInvoiceList)
        	{
        		createInvoiceListAux.add(mom.toObject(CreateInvoice.class, invoice));
        	}
        }
        
        CreateInvoicebatch createInvoiceBatch = mom.toObject(CreateInvoicebatch.class, 
            new MapBuilder()
                            .with("batchtitle", batchTitle)
                            .with("datecreated", dateCreated)
                            .with("createInvoice", coalesceList(createInvoiceList))
                            .build()
            );

        Function function = new Function();
        function.getCmd().add(createInvoiceBatch);
        function.setControlid(functionControlId);
        
        return operationWithRequest(inicializeRequest(function));
    }
    
    /**
     * Creates and adjustement. 
     */
    @Processor
    public Response createAradjustment(String functionControlId,
                                       String customerId,
                                       Map<String, Object> dateCreated,
                                       @Optional Map<String, Object> datePosted,
                                       @Optional String batchKey,
                                       @Optional String adjustmentNo,
                                       @Optional String invoiceNo,
                                       @Optional String description,
                                       @Optional String externalId,
                                       @Optional String basecurr,
                                       @Optional String currency,
                                       @Optional ExchType exchType,
                                       @Optional List<Map<String, Object>> exchRateDateOrExchRateTypeOrExchRate,
                                       @Optional String nogl,
                                       List<Map<String, Object>> arAdjustmentItems
                                       ) throws JAXBException
    {
        List<Object> exchRateDateOrExchRateTypeOrExchRateAux = new ArrayList<Object>();
        if(exchRateDateOrExchRateTypeOrExchRate != null){
        	for(Map<String, Object> exch : exchRateDateOrExchRateTypeOrExchRate)
        	{
        		exchRateDateOrExchRateTypeOrExchRateAux.add(mom.toObject(exchType.getRequestType(), exch));
        	}
        }
        CreateAradjustment createArAdjustment = mom.toObject(CreateAradjustment.class, 
            new MapBuilder().with("customerid", fromSingleValue(customerId))
                            .with("datecreated", dateCreated)
                            .with("dateposted", datePosted)
                            .with("batchkey", fromSingleValue(batchKey))
                            .with("invoiceno", invoiceNo)
                            .with("description", description)
                            .with("externalid", externalId)
                            .with("currency", currency)
                            .with("exchratedateOrExchratetypeOrExchrate", coalesceList(exchRateDateOrExchRateTypeOrExchRateAux))
                            .with("nogl", nogl)
                            .with("aradjustmentitems", nullifyEmptyListWrapper("lineitem", arAdjustmentItems, Lineitem.class))
                            .build()
            );

        Function function = new Function();
        function.getCmd().add(createArAdjustment);
        function.setControlid(functionControlId);
        
        return operationWithRequest(inicializeRequest(function));
    }
    
    @Processor
    public Response createSotransaction(String functionControlId,
                                        String transactionType,
                                        Map<String, Object> dateCreated, 
                                        @Optional String createdFrom,
                                        String customerId, 
                                        @Optional String documentNo,
                                        @Optional String referenceNo,
                                        @Optional String termName,
                                        @Optional Map<String, Object> dateDue,
                                        @Optional String message,
                                        @Optional String shippingMethod,
                                        @Optional Map<String, Object> shipTo,
                                        @Optional Map<String, Object> billTo,
                                        @Optional String externalId,
                                        @Optional String baseCurr,
                                        @Optional String currency,
                                        @Optional List<Object> exchrateDateOrExchrateTypeOrExchrate,
                                        @Optional String vsoePriceList,
                                        @Optional Map<String, Object> customFields,
                                        Map<String, Object> soTransItems,
                                        @Optional Map<String, Object> subTotals
                                        ) throws JAXBException
    {
        CreateSotransaction createSotransaction = mom.toObject(CreateSotransaction.class, 
            new MapBuilder().with("transactiontype", transactionType)
                            .with("datecreated", dateCreated)
                            .with("createdfrom", createdFrom)
                            .with("customerid", fromSingleValue(customerId))
                            .with("documentno", documentNo)
                            .with("referenceno", referenceNo)
                            .with("termname", fromSingleValue(termName))
                            .with("datedue", dateDue)
                            .with("message", message)
                            .with("shippingmethod", shippingMethod)
                            .with("shipto", shipTo)
                            .with("billto", billTo)
                            .with("externalid", externalId)
                            .with("basecurr", baseCurr)
                            .with("currency", currency)
                            .with("exchratedateOrExchratetypeOrExchrate", coalesceList(exchrateDateOrExchrateTypeOrExchrate))
                            .with("vsoepricelist", vsoePriceList)
                            .with("customfields", customFields)
                            .with("sotransitems", soTransItems)
                            .with("subtotals", subTotals)
                            .build()
            );

        Function function = new Function();
        function.getCmd().add(createSotransaction);
        function.setControlid(functionControlId);
        
        return operationWithRequest(inicializeRequest(function));
    }
    
	protected Map<String,Object> fromSingleValue(final Object value){
    	return value == null ? null : Collections.singletonMap("value", value);
    }
    
    
    @Processor
    public Response getList(String functionControlId,
                            String obj,
                            @Optional String start,
                            @Optional String maxItems, 
                            @Optional String showPrivate, 
                            @Optional Map<String, Object> filter,
                            @Optional Map<String, Object> sorts,
                            @Optional Map<String, Object> fields
                            ) throws JAXBException
    {
        GetList getList = mom.toObject(GetList.class, 
            new MapBuilder().with("object", obj)
                            .with("start", start)
                            .with("maxitems", maxItems)
                            .with("filter", filter)
                            .with("sorts", sorts)
                            .with("fields", fields)
                            .build()
            );

        Function function = new Function();
        function.getCmd().add(getList);
        function.setControlid(functionControlId);
        
        return operationWithRequest(inicializeRequest(function));
    }
    
    @Processor
    public Response get(String functionControlId,
                        String obj,
                        String key, 
                        @Optional String externalKey,
                        @Optional Map<String, Object> fields
                        ) throws JAXBException
    {
        Get get = mom.toObject(Get.class, 
            new MapBuilder().with("object", obj)
                            .with("key", key)
                            .with("externalkey", externalKey)
                            .with("fields", fields)
                            .build()
            );

        Function function = new Function();
        function.getCmd().add(get);
        function.setControlid(functionControlId);
        
        return operationWithRequest(inicializeRequest(function));
    }
    
    public Response sendRequest(final Request request) throws JAXBException
    {
        try
        {
            return intacctImplementation.executeOperation(request);
        }
        // Here we catch everything and we wrap it in our domain exception
        catch (Throwable ex)
        {
            throw new IntacctException("There was an error sending the request to the server."
                                       + " Please check the cause for further information", ex);
        }

    }
    
    /** Reconoce la operacion con valores default setteados en el config */
    @Processor
    public Response operationWithRequest(final Request request) throws JAXBException
    {
        return sendRequest(request);
    }
    
    @PostConstruct
    public void init()
    {
        if (intacctImplementation == null )
        {
            intacctImplementation = new JerseySslIntacctFacade(URL);
        }
        mom.setPropertyStyle(CXFStyle.STYLE);
    }
    
    private Request inicializeRequest(Function function)
    {
        final Request request = new Request();
        final Control control = new Control();
        control.setSenderid(senderId);
        control.setPassword(controlPassword);
        control.setControlid(controlid);
        control.setUniqueid(uniqueid);
        control.setDtdversion("2.1");
        request.setControl(control);
        final Operation operation = new Operation();
        request.getOperation().add(operation);
        final Authentication authentication = new Authentication();
        final Login login = new Login();
        login.setUserid(userid);
        login.setPassword(userPassword);
        login.setCompanyid(companyid);
        authentication.getLoginOrSessionid().add(login);
        operation.setAuthentication(authentication);
        final Content content = new Content();
        content.getFunction().add(function);
        operation.getContent().add(content);
        
        return request;
    }
    
    /**
     * Returns the senderId.
     * 
     * @return  with the senderId.
     */
    
    public String getSenderId()
    {
        return senderId;
    }

    /**
     * Sets the senderId. 
     *
     * @param senderId  with the senderId.
     */
    
    public void setSenderId(String senderId)
    {
        this.senderId = senderId;
    }

    /**
     * Returns the controlPassword.
     * 
     * @return  with the controlPassword.
     */
    
    public String getControlPassword()
    {
        return controlPassword;
    }

    /**
     * Sets the controlPassword. 
     *
     * @param controlPassword  with the controlPassword.
     */
    
    public void setControlPassword(String controlPassword)
    {
        this.controlPassword = controlPassword;
    }

    /**
     * Returns the controlid.
     * 
     * @return  with the controlid.
     */
    
    public String getControlid()
    {
        return controlid;
    }

    /**
     * Sets the controlid. 
     *
     * @param controlid  with the controlid.
     */
    
    public void setControlid(String controlid)
    {
        this.controlid = controlid;
    }

    /**
     * Returns the uniqueid.
     * 
     * @return  with the uniqueid.
     */
    
    public String getUniqueid()
    {
        return uniqueid;
    }

    /**
     * Sets the uniqueid. 
     *
     * @param uniqueid  with the uniqueid.
     */
    
    public void setUniqueid(String uniqueid)
    {
        this.uniqueid = uniqueid;
    }

    /**
     * Returns the userid.
     * 
     * @return  with the userid.
     */
    
    public String getUserid()
    {
        return userid;
    }

    /**
     * Sets the userid. 
     *
     * @param userid  with the userid.
     */
    
    public void setUserid(String userid)
    {
        this.userid = userid;
    }

    /**
     * Returns the userPassword.
     * 
     * @return  with the userPassword.
     */
    
    public String getUserPassword()
    {
        return userPassword;
    }

    /**
     * Sets the userPassword. 
     *
     * @param userPassword  with the userPassword.
     */
    
    public void setUserPassword(String userPassword)
    {
        this.userPassword = userPassword;
    }

    /**
     * Returns the companyid.
     * 
     * @return  with the companyid.
     */
    
    public String getCompanyid()
    {
        return companyid;
    }

    /**
     * Sets the companyid. 
     *
     * @param companyid  with the companyid.
     */
    
    public void setCompanyid(String companyid)
    {
        this.companyid = companyid;
    }

    /**
     * Returns the intacctImplementation.
     * 
     * @return  with the intacctImplementation.
     */
    
    public IntacctFacade getIntacctImplementation()
    {
        return intacctImplementation;
    }

    /**
     * Sets the intacctImplementation. 
     *
     * @param intacctImplementation  with the intacctImplementation.
     */
    
    public void setIntacctImplementation(IntacctFacade intacctImplementation)
    {
        this.intacctImplementation = intacctImplementation;
    }
    
    @SuppressWarnings("unchecked")
    private <T> List<T> coalesceList(List<T> list )
    {
        return (List<T>) ((list == null) ? Collections.emptyList() : list);
    }
    
    /**
     * @param propertyName
     * @param value
     * @param clazz
     * @return
     */
    private Object nullifyEmptyListWrapper(final String propertyName,
                                       final List<Map<String, Object>> value,
                                       final Class<?> clazz)
    {
        return mom.nullifyEmptyListWrapper(propertyName, value, clazz);
    }

}
