/*
 * $Id$
 * --------------------------------------------------------------------------------------
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */

package org.mule.module.intacct.config;

import org.mule.config.spring.handlers.AbstractMuleNamespaceHandler;
import org.mule.config.spring.parsers.generic.OrphanDefinitionParser;
import org.mule.module.intacct.IntacctCloudConnector;

/**
 * This namespace handler for spring for intacct
 */
public class IntacctNamespaceHandler extends AbstractMuleNamespaceHandler
{

    private static final String [] API_FUNCTIONS = {
        "create_apaccountlabel",
        "create_apadjustment",
        "create_apadjustmentbatch",
        "create_araccountlabel",
        "create_aradjustment",
        "create_aradjustmentbatch",
        "create_arpayment",
        "create_arpaymentbatch",
        "create_bill",
        "create_recurringbill",
        "create_billbatch",
        "create_checkingaccount",
        "create_savingsaccount",
        "update_checkingaccount",
        "update_savingsaccount",
        "delete_checkingaccount",
        "delete_savingsaccount",
        "create_contact",
        "create_customer",
        "create_department",
        "create_employee",
        "create_expensereport",
        "create_expensereportbatch",
        "create_expensetype",
        "create_glaccount",
        "create_statglaccount",
        "create_gltransaction",
        "delete_gltransaction",
        "create_recurringgltransaction",
        "delete_recurringgltransaction",
        "create_statgltransaction",
        "create_recurringstatgltrans",
        "delete_recurringstatgltrans",
        "create_invoice",
        "create_recurringinvoice",
        "create_invoicebatch",
        "create_journal",
        "create_location",
        "create_statjournal",
        "create_project",
        "update_project",
        "delete_project",
        "create_class",
        "delete_class",
        "create_vendor",
        "delete_apaccountlabel",
        "delete_apadjustment",
        "create_locationgroup",
        "delete_araccountlabel",
        "delete_aradjustment",
        "delete_bill",
        "delete_recurringbill",
        "delete_contact",
        "delete_customer",
        "delete_department",
        "delete_employee",
        "delete_expensereport",
        "delete_expensetype",
        "delete_glaccount",
        "delete_statglaccount",
        "delete_invoice",
        "delete_recurringinvoice",
        "delete_journal",
        "delete_statjournal",
        "delete_location",
        "delete_vendor",
        "get",
        "get_accountbalances",
        "get_accountgroupdetails",
        "get_apadjustment",
        "get_aradjustment",
        "get_bill",
        "get_expensereport",
        "get_invoice",
        "get_list",
        "get_trialbalance",
        "get_myclients",
        "init_session",
        "update_apaccountlabel",
        "update_araccountlabel",
        "update_contact",
        "update_customer",
        "update_department",
        "update_invoice",
        "update_bill",
        "update_apadjustment",
        "update_aradjustment",
        "update_employee",
        "update_expensereport",
        "update_expensetype",
        "update_glaccount",
        "update_statglaccount",
        "update_journal",
        "update_location",
        "update_vendor",
        "create_paymentrequest",
        "reclassify_bill",
        "reclassify_invoice",
        "delete_paymentrequest",
        "create_appayment",
        "create_stkittransaction",
        "create_ictransaction",
        "update_ictransaction",
        "create_sotransaction",
        "update_sotransaction",
        "create_recursotransaction",
        "delete_recursotransaction",
        "create_potransaction",
        "update_potransaction",
        "get_salestotals",
        "get_icitemtotals",
        "record_cctransaction",
        "record_wucctransactions",
        "record_wureceipts",
        "record_wudisbursements",
        "record_wuadjjournalentries",
        "record_wujournalentries",
        "get_companyprefs",
        "set_companyprefs",
        "get_applications",
        "record_otherreceipt",
        "record_deposit",
        "create_territory",
        "delete_territory",
        "update_territory",
        "apply_arpayment",
        "delete_sotransaction",
        "delete_potransaction",
        "delete_ictransaction",
        "create_item",
        "update_item",
        "delete_item",
        "create_sopricelist",
        "delete_sopricelist",
        "update_sopricelist",
        "create_popricelist",
        "delete_popricelist",
        "update_popricelist",
        "create_vsoepricelist",
        "update_vsoepricelist",
        "delete_vsoepricelist",
        "create_vsoeitempricelist",
        "update_vsoeitempricelist",
        "delete_vsoeitempricelist",
        "create_invpricelistentry",
        "delete_invpricelistentry",
        "update_invpricelistentry",
        "get_closedbooksdate",
        "get_araging",
        "delete_arpayment",
        "create_customerachinfo",
        "update_customerachinfo",
        "delete_customerachinfo",
        "create_customerchargecard",
        "update_customerchargecard",
        "delete_customerchargecard",
        "create_customerbankaccount",
        "update_customerbankaccount",
        "delete_customerbankaccount",
        "create_taxdetail",
        "update_taxdetail",
        "delete_taxdetail",
        "create_taxschedule",
        "update_taxschedule",
        "delete_taxschedule",
        "create_taxscheduledetail",
        "delete_taxscheduledetail",
        "create_contacttaxgroup",
        "delete_contacttaxgroup",
        "create_itemtaxgroup",
        "delete_itemtaxgroup",
        "create_taxschedulemap",
        "delete_taxschedulemap",
        "describe",
        "reconcile_bank",
        "reverse_bill",
        "reverse_appayment",
        "create_apterm",
        "update_apterm",
        "delete_apterm",
        "create_arterm",
        "update_arterm",
        "delete_arterm",
        "create_timesheet",
        "update_timesheet",
        "delete_timesheet",
        "create_task",
        "update_task",
        "delete_task",
        "create_allocation",
        "update_allocation",
        "delete_allocation",
        "update_cctransaction",
        "reverse_cctransaction",
        };
    
    public void init()
    {
        registerMuleBeanDefinitionParser("config", 
            new OrphanDefinitionParser(IntacctCloudConnector.class, true));
        
        for (String method : API_FUNCTIONS)
        {
            registerMuleBeanDefinitionParser(method, new DTOChildDefinitionParserNoAttributes(
                "messageProcessor", DTOEvaluationInvokerMessageProcessorFactoryBean.class, "arguments"));
        }
        
        
        
        registerMuleBeanDefinitionParser("execute-function", 
            new DTOChildDefinitionParser("messageProcessor",
                DTOEvaluationInvokerMessageProcessorFactoryBean.class, "arguments"));
        
        registerMuleBeanDefinitionParser("execute-request", 
            new DTOChildDefinitionParser("messageProcessor",
                DTOEvaluationInvokerMessageProcessorFactoryBean.class, "arguments"));
    }
}
